-- 손님 예약 화면(/book/tee-time, /book/indoor, /book/lookup)을 FastAPI 없이 돌린다.
--
-- 왜: 예약 API(`pelhamhills-api.fly.dev`)가 2026-09-16 Fly.io 체험 종료로 꺼졌다.
-- 정적 사이트(`output: "export"`)는 비밀 키를 들 곳이 없으므로, 브라우저는 공개(anon)
-- 키로 **아래 함수들만** 부른다. 테이블은 그대로 잠겨 있다.
--
-- 규칙
-- - 공유 프로젝트다(GPS 앱·다른 앱과 같은 DB). 테이블·함수 전부 `pelham_` 접두사.
-- - 테이블에는 anon/authenticated 정책을 만들지 않는다(0001·0002 와 같다). 손님이
--   볼 수 있는 것은 함수가 돌려주는 것뿐이다:
--     티타임  → 남은 자리 수와 요금. 다른 손님의 예약 행(이름·전화·이메일)은 절대 안 나간다.
--     실내골프 → 빈 베이 수. 코드 조회는 그 코드의 예약 한 건만(예전 API 와 같다).
-- - 정원 검사와 저장은 한 트랜잭션 안에서 advisory lock 으로 묶는다. FastAPI 의
--   `threading.RLock` 자리를 대신한다. ⚠️ Fly 서버를 다시 켜서 같은 테이블에 쓰게
--   하면 두 쪽의 잠금이 서로를 모른다 — 한쪽만 쓰게 할 것.
-- - 영업 규칙(격자·요금·휴무일)은 `backend/api/routes/tee_sheet.py`,
--   `backend/api/routes/simulator.py` 와 같은 값이다. 바꾸면 양쪽을 같이 바꾼다.
-- - 오류는 `PTxxx` SQLSTATE 로 올린다. PostgREST 가 그 숫자를 HTTP 상태로 쓴다
--   (PT400 → 400, PT409 → 409). 메시지는 손님에게 그대로 보여도 되는 문장이다.
-- - 시각 판단(오늘·지난 시간)은 클럽 현지 시간 America/Toronto 로 한다.
--
-- 실행: SQL editor 에 이 파일 전체를 붙여 한 번. 다시 실행해도 안전하다(시드는 비어 있을 때만).

-- 0002 는 RLS 만 켰다(정책 없음 → 0행). 이제 공개 키가 이 DB 에 실제로 들어오므로
-- 테이블 권한 자체도 걷어 낸다. service_role(Fly 백엔드)은 영향이 없다.
revoke all on public.pelham_tee_bookings from anon, authenticated;

-- ===== 실내 골프(시뮬레이터) ==========================================

create table if not exists public.pelham_sim_bays (
  id           integer primary key,
  bay_number   integer not null unique,
  bay_type     text not null check (bay_type in ('right_handed', 'left_right', 'vip')),
  hourly_rate  numeric(8,2) not null check (hourly_rate >= 0),
  is_active    boolean not null default true
);

create table if not exists public.pelham_sim_reservations (
  id                 bigint generated by default as identity primary key,
  bay_id             integer not null references public.pelham_sim_bays (id),
  booking_date       date not null,
  start_minutes      integer not null check (start_minutes between 0 and 1439),
  duration_hours     integer not null check (duration_hours between 1 and 5),
  player_count       integer not null check (player_count between 1 and 4),
  customer_name      text not null,
  customer_email     text not null,
  phone              text not null default '',
  notes              text not null default '',
  confirmation_code  text not null unique,
  total_price        numeric(8,2),
  status             text not null default 'confirmed',
  created_at         timestamptz not null default now(),
  updated_at         timestamptz not null default now()
);

create index if not exists pelham_sim_reservations_date_idx
  on public.pelham_sim_reservations (booking_date);

alter table public.pelham_sim_bays enable row level security;
alter table public.pelham_sim_reservations enable row level security;
revoke all on public.pelham_sim_bays, public.pelham_sim_reservations from anon, authenticated;

comment on table public.pelham_sim_reservations is
  'Pelham Hills 실내 골프 예약 (PII 포함). 손님은 pelham_sim_* 함수로만 닿는다.';

-- 시드: `backend/data/simulator.json` (2026-09-07 사본). 예약은 0건이었다.
insert into public.pelham_sim_bays (id, bay_number, bay_type, hourly_rate, is_active)
select * from (values
  (1, 1, 'right_handed', 20.00, true),
  (2, 2, 'right_handed', 20.00, true),
  (3, 3, 'right_handed', 20.00, true),
  (4, 4, 'left_right',   20.00, true),
  (5, 5, 'vip',          25.00, true)
) as seed (id, bay_number, bay_type, hourly_rate, is_active)
where not exists (select 1 from public.pelham_sim_bays);

-- ===== 프로 샵 상품 ====================================================
-- 직원 화면(POS)은 아직 이 테이블을 쓰지 않는다 — 직원 로그인이 생길 때 붙인다.
-- 지금은 Fly 디스크에 갇힌 데이터를 잃지 않게 옮겨 두는 것이 목적이다.

create table if not exists public.pelham_retail_products (
  id             integer primary key,
  sku            text not null unique,
  name           text not null,
  category       text not null,
  price          integer not null check (price >= 0),   -- 센트
  cost           integer not null check (cost >= 0),    -- 센트
  stock          integer,                               -- null = 재고를 세지 않는 대여 품목
  reorder_point  integer not null default 0,
  is_active      boolean not null default true,
  created_at     timestamptz not null default now(),
  updated_at     timestamptz not null default now()
);

-- 판매는 티 시트와 같은 모양(인덱스 컬럼 + 원본 doc). `retail.json` 의 판매는 0건이었다.
create table if not exists public.pelham_retail_sales (
  id             integer primary key,
  business_date  date not null,
  doc            jsonb not null,
  created_at     timestamptz not null default now()
);

alter table public.pelham_retail_products enable row level security;
alter table public.pelham_retail_sales enable row level security;
revoke all on public.pelham_retail_products, public.pelham_retail_sales from anon, authenticated;

-- 시드: `backend/data/retail.json` (2026-09-08 사본).
insert into public.pelham_retail_products
  (id, sku, name, category, price, cost, stock, reorder_point, is_active, created_at, updated_at)
select * from (values
  (1, 'PV1-DZ', 'Titleist Pro V1 (Dozen)', 'Balls', 8499, 5900, 48, 12, true, '2026-09-08T07:05:02.744080+00:00'::timestamptz, '2026-09-08T07:05:02.744080+00:00'::timestamptz),
  (2, 'CHRM-DZ', 'Callaway Chrome Soft (Dozen)', 'Balls', 7999, 5500, 36, 12, true, '2026-09-08T07:05:02.744080+00:00', '2026-09-08T07:05:02.744080+00:00'),
  (3, 'TM-QI10-D', 'TaylorMade Qi10 Driver', 'Equipment', 69999, 52000, 4, 2, true, '2026-09-08T07:05:02.744080+00:00', '2026-09-08T07:05:02.744080+00:00'),
  (4, 'VKY-SM10-56', 'Titleist Vokey SM10 Wedge 56', 'Equipment', 24999, 17500, 6, 2, true, '2026-09-08T07:05:02.744080+00:00', '2026-09-08T07:05:02.744080+00:00'),
  (5, 'SC-NP2-34', 'Scotty Cameron Newport 2 Putter (34")', 'Equipment', 64999, 48000, 2, 1, true, '2026-09-08T07:05:02.744080+00:00', '2026-09-08T07:05:02.744080+00:00'),
  (6, 'FJ-POLO-M', 'FootJoy ProDry Polo (M)', 'Apparel', 8999, 4800, 14, 6, true, '2026-09-08T07:05:02.744080+00:00', '2026-09-08T07:05:02.744080+00:00'),
  (7, 'PH-CAP-ADJ', 'Pelham Hills Adjustable Cap', 'Apparel', 3499, 1400, 30, 10, true, '2026-09-08T07:05:02.744080+00:00', '2026-09-08T07:05:02.744080+00:00'),
  (8, 'SM-RAIN-L', 'Sun Mountain Rain Jacket (L)', 'Apparel', 19999, 12000, 5, 3, true, '2026-09-08T07:05:02.744080+00:00', '2026-09-08T07:05:02.744080+00:00'),
  (9, 'FJ-GLV-ML', 'FootJoy WeatherSof Glove (ML)', 'Accessories', 2299, 1150, 40, 12, true, '2026-09-08T07:05:02.744080+00:00', '2026-09-08T07:05:02.744080+00:00'),
  (10, 'TEE-BMB-50', 'Bamboo Tees 2.75" (50 pack)', 'Accessories', 999, 380, 60, 20, true, '2026-09-08T07:05:02.744080+00:00', '2026-09-08T07:05:02.744080+00:00'),
  (11, 'PH-TWL-TRI', 'Pelham Hills Tri-Fold Towel', 'Accessories', 2999, 1300, 18, 6, true, '2026-09-08T07:05:02.744080+00:00', '2026-09-08T07:05:02.744080+00:00'),
  (12, 'DVT-MRK-SET', 'Divot Tool & Ball Marker Set', 'Accessories', 1499, 620, 25, 10, true, '2026-09-08T07:05:02.744080+00:00', '2026-09-08T07:05:02.744080+00:00'),
  (13, 'GTR-591', 'Gatorade 591 mL', 'Food & Beverage', 399, 145, 72, 24, true, '2026-09-08T07:05:02.744080+00:00', '2026-09-08T07:05:02.744080+00:00'),
  (14, 'CLIF-BAR', 'Clif Bar', 'Food & Beverage', 349, 160, 45, 15, true, '2026-09-08T07:05:02.744080+00:00', '2026-09-08T07:05:02.744080+00:00'),
  (15, 'CART-18', 'Power Cart Rental (18 holes)', 'Rentals', 2500, 0, null, 0, true, '2026-09-08T07:05:02.744080+00:00', '2026-09-08T07:05:02.744080+00:00'),
  (16, 'CLUBS-18', 'Rental Clubs (18 holes)', 'Rentals', 4500, 0, null, 0, true, '2026-09-08T07:05:02.744080+00:00', '2026-09-08T07:05:02.744080+00:00')
) as seed (id, sku, name, category, price, cost, stock, reorder_point, is_active, created_at, updated_at)
where not exists (select 1 from public.pelham_retail_products);

-- ===== 공용 헬퍼 =======================================================

-- 클럽 현지 시각. 테스트가 시계를 고정할 수 있게 `pelham.now` 설정을 먼저 본다.
create or replace function public.pelham_local_now()
returns timestamp
language sql
stable
set search_path = ''
as $$
  select coalesce(nullif(current_setting('pelham.now', true), '')::timestamptz, now())
         at time zone 'America/Toronto'
$$;

-- pydantic 이 JSON 으로 내보내는 것과 같은 UTC ISO 문자열.
create or replace function public.pelham_iso(ts timestamptz)
returns text
language sql
immutable
set search_path = ''
as $$
  select to_char(ts at time zone 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.US"Z"')
$$;

create or replace function public.pelham_fail(status text, message text)
returns void
language plpgsql
set search_path = ''
as $$
begin
  raise exception using errcode = 'PT' || status, message = message;
end;
$$;

-- ===== 실내 골프 함수 ==================================================
-- 영업: 수~일 14:00-22:00, 월·화 휴무, 15분 격자, 1-5시간, 최대 4명.

create or replace function public.pelham_sim_availability(
  p_date date,
  p_bay_type text default 'right_handed',
  p_duration_hours integer default 1
)
returns jsonb
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
  open_min constant integer := 14 * 60;
  close_min constant integer := 22 * 60;
  span integer;
  local_now timestamp := public.pelham_local_now();
  label text;
  total integer;
  free_bays integer;
  slots jsonb := '[]'::jsonb;
  base jsonb;
  start_min integer;
begin
  if p_date is null then
    perform public.pelham_fail('400', 'Invalid date format. Use YYYY-MM-DD');
  end if;
  if p_duration_hours is null or p_duration_hours not between 1 and 5 then
    perform public.pelham_fail('400', 'Duration must be between 1 and 5 hours.');
  end if;
  span := p_duration_hours * 60;
  label := initcap(replace(coalesce(p_bay_type, ''), '_', ' '));

  base := jsonb_build_object(
    'date', to_char(p_date, 'YYYY-MM-DD'),
    'bay_type', p_bay_type,
    'duration_hours', p_duration_hours,
    'is_closed', false,
    'available_slots', '[]'::jsonb,
    'reason', null
  );

  if extract(isodow from p_date) in (1, 2) then
    return base || jsonb_build_object(
      'is_closed', true,
      'reason', 'The simulator is closed on Mondays and Tuesdays.'
    );
  end if;

  select count(*) into total
    from public.pelham_sim_bays b
   where b.is_active and b.bay_type = p_bay_type;
  if total = 0 then
    return base || jsonb_build_object('reason', format('No bays are configured for %s.', label));
  end if;

  start_min := open_min;
  while start_min + span <= close_min loop
    -- 오늘의 지난 시각은 팔지 않는다.
    if p_date > local_now::date
       or (p_date = local_now::date
           and start_min > extract(hour from local_now) * 60 + extract(minute from local_now)) then
      select count(*) into free_bays
        from public.pelham_sim_bays b
       where b.is_active and b.bay_type = p_bay_type
         and not exists (
           select 1 from public.pelham_sim_reservations r
            where r.bay_id = b.id
              and r.booking_date = p_date
              and r.status = 'confirmed'
              and r.start_minutes < start_min + span
              and r.start_minutes + r.duration_hours * 60 > start_min
         );
      if free_bays > 0 then
        slots := slots || jsonb_build_object(
          'time', lpad((start_min / 60)::text, 2, '0') || ':' || lpad((start_min % 60)::text, 2, '0'),
          'available_bays', free_bays,
          'total_bays', total
        );
      end if;
    end if;
    start_min := start_min + 15;
  end loop;

  if jsonb_array_length(slots) = 0 then
    return base || jsonb_build_object(
      'reason',
      case when p_date < local_now::date
           then 'That date has already passed.'
           else format('Every %s bay is booked for %s hour%s on this date.',
                       label, p_duration_hours, case when p_duration_hours > 1 then 's' else '' end)
      end
    );
  end if;
  return base || jsonb_build_object('available_slots', slots);
end;
$$;

create or replace function public.pelham_sim_reserve(p jsonb)
returns jsonb
language plpgsql
volatile
security definer
set search_path = ''
as $$
declare
  open_min constant integer := 14 * 60;
  close_min constant integer := 22 * 60;
  local_now timestamp := public.pelham_local_now();
  v_date date;
  v_type text := p->>'bay_type';
  v_duration integer;
  v_players integer;
  v_name text := btrim(coalesce(p->>'customer_name', ''));
  v_email text := btrim(coalesce(p->>'customer_email', ''));
  v_phone text := btrim(coalesce(p->>'phone', ''));
  v_notes text := btrim(coalesce(p->>'notes', ''));
  v_start integer;
  v_bay public.pelham_sim_bays;
  v_code text;
  v_row public.pelham_sim_reservations;
  m text[];
begin
  begin
    v_date := (p->>'date')::date;
  exception when others then
    v_date := null;
  end;
  if v_date is null or coalesce(p->>'date', '') !~ '^\d{4}-\d{2}-\d{2}$' then
    perform public.pelham_fail('400', 'Invalid date format. Use YYYY-MM-DD');
  end if;
  if extract(isodow from v_date) in (1, 2) then
    perform public.pelham_fail('400', 'The simulator is closed on Mondays and Tuesdays.');
  end if;
  if v_type is null or v_type not in ('right_handed', 'left_right', 'vip') then
    perform public.pelham_fail('400', format('Unknown bay type: %s', coalesce(v_type, '')));
  end if;
  if coalesce(p->>'duration_hours', '') !~ '^\d+$' or (p->>'duration_hours')::integer not between 1 and 5 then
    perform public.pelham_fail('400', 'Duration must be between 1 and 5 hours.');
  end if;
  v_duration := (p->>'duration_hours')::integer;
  v_players := coalesce(nullif(p->>'player_count', ''), '1')::integer;
  if v_players not between 1 and 4 then
    perform public.pelham_fail('400', 'Player count must be between 1 and 4.');
  end if;
  if v_name = '' then
    perform public.pelham_fail('400', 'Name is required');
  end if;
  if v_email = '' then
    perform public.pelham_fail('400', 'Email is required');
  end if;
  if length(v_name) > 120 or length(v_email) > 254 or length(v_phone) > 40 or length(v_notes) > 1000
     or position('@' in v_email) = 0 then
    perform public.pelham_fail('400', 'Please check your name, email, phone and notes.');
  end if;

  m := regexp_match(coalesce(p->>'start_time', ''), '^(\d{1,2}):(\d{2})$');
  if m is null or m[1]::integer > 23 or m[2]::integer > 59 then
    perform public.pelham_fail('400', 'Invalid time format. Use HH:MM');
  end if;
  v_start := m[1]::integer * 60 + m[2]::integer;
  if v_start < open_min or v_start + v_duration * 60 > close_min then
    perform public.pelham_fail('400', 'Requested time is outside operating hours (2:00 PM - 10:00 PM).');
  end if;
  if v_date < local_now::date
     or (v_date = local_now::date
         and v_start <= extract(hour from local_now) * 60 + extract(minute from local_now)) then
    perform public.pelham_fail('400', 'That time has already passed. Please pick a later time.');
  end if;

  -- 그날의 빈 베이 확인과 기록을 한 잠금 안에서.
  perform pg_advisory_xact_lock(hashtext('pelham_sim:' || v_date::text));

  select b.* into v_bay
    from public.pelham_sim_bays b
   where b.is_active and b.bay_type = v_type
     and not exists (
       select 1 from public.pelham_sim_reservations r
        where r.bay_id = b.id
          and r.booking_date = v_date
          and r.status = 'confirmed'
          and r.start_minutes < v_start + v_duration * 60
          and r.start_minutes + r.duration_hours * 60 > v_start
     )
   order by b.bay_number
   limit 1;

  if v_bay.id is null then
    if not exists (select 1 from public.pelham_sim_bays b where b.is_active and b.bay_type = v_type) then
      perform public.pelham_fail('404', format('No bays are configured for %s.', initcap(replace(v_type, '_', ' '))));
    end if;
    perform public.pelham_fail('409', 'Time slot already booked');
  end if;

  loop
    v_code := upper(substr(replace(gen_random_uuid()::text, '-', ''), 1, 10));
    exit when not exists (select 1 from public.pelham_sim_reservations r where r.confirmation_code = v_code);
  end loop;

  insert into public.pelham_sim_reservations
    (bay_id, booking_date, start_minutes, duration_hours, player_count,
     customer_name, customer_email, phone, notes, confirmation_code, total_price)
  values
    (v_bay.id, v_date, v_start, v_duration, v_players,
     v_name, v_email, v_phone, v_notes, v_code, v_bay.hourly_rate * v_duration)
  returning * into v_row;

  return jsonb_build_object(
    'id', v_row.id,
    'confirmation_code', v_row.confirmation_code,
    'bay_type', initcap(replace(v_bay.bay_type, '_', ' ')),
    'bay_number', v_bay.bay_number,
    'date', to_char(v_row.booking_date, 'YYYY-MM-DD'),
    'start_time', lpad((v_start / 60)::text, 2, '0') || ':' || lpad((v_start % 60)::text, 2, '0'),
    'duration_hours', v_row.duration_hours,
    'player_count', v_row.player_count,
    'total_price', v_row.total_price
  );
end;
$$;

-- 확인 코드로 한 건. 없으면 null (화면이 "찾을 수 없음" 을 띄운다).
create or replace function public.pelham_sim_lookup(p_code text)
returns jsonb
language sql
stable
security definer
set search_path = ''
as $$
  select jsonb_build_object(
    'id', r.id,
    'confirmation_code', r.confirmation_code,
    'bay_type', initcap(replace(b.bay_type, '_', ' ')),
    'bay_number', b.bay_number,
    'date', to_char(r.booking_date, 'YYYY-MM-DD'),
    'start_time', lpad((r.start_minutes / 60)::text, 2, '0') || ':' || lpad((r.start_minutes % 60)::text, 2, '0'),
    'duration_hours', r.duration_hours,
    'player_count', r.player_count,
    'customer_name', r.customer_name,
    'customer_email', r.customer_email,
    'total_price', r.total_price,
    'status', r.status,
    'created_at', public.pelham_iso(r.created_at)
  )
  from public.pelham_sim_reservations r
  join public.pelham_sim_bays b on b.id = r.bay_id
  where r.confirmation_code = upper(btrim(coalesce(p_code, '')))
    and btrim(coalesce(p_code, '')) ~* '^[0-9a-f]{10}$'
$$;

-- ===== 티타임 함수 =====================================================
-- 격자: 6:40 AM ~ 6:58 PM, 9분 간격, 한 티타임 4자리(여러 예약이 나눠 가짐).
-- 요금: 토·일 58.41, 그 외 47.79. 테이블은 0002 의 pelham_tee_bookings.

create or replace function public.pelham_tee_label(minutes integer)
returns text
language sql
immutable
set search_path = ''
as $$
  select (case when (minutes / 60) % 12 = 0 then 12 else (minutes / 60) % 12 end)::text
         || ':' || lpad((minutes % 60)::text, 2, '0')
         || case when minutes / 60 < 12 then ' AM' else ' PM' end
$$;

create or replace function public.pelham_tee_rate(p_date date)
returns numeric
language sql
immutable
set search_path = ''
as $$
  select case when extract(isodow from p_date) in (6, 7) then 58.41 else 47.79 end
$$;

-- 손님이 살 수 있는 티타임. 막힌(blocked) 티타임과 오늘의 지난 시각은 뺀다.
-- 돌려주는 것은 시각·요금·남은 자리뿐이다.
create or replace function public.pelham_tee_availability(p_date date)
returns jsonb
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
  local_now timestamp := public.pelham_local_now();
  now_min integer := extract(hour from local_now) * 60 + extract(minute from local_now);
  result jsonb;
begin
  if p_date is null then
    perform public.pelham_fail('422', '''date'' must be an ISO date (YYYY-MM-DD)');
  end if;

  with grid as (
    select m as minutes, public.pelham_tee_label(m) as label
      from generate_series(6 * 60 + 40, 18 * 60 + 58, 9) as m
  ),
  day as (
    select t.tee_time,
           t.status,
           jsonb_array_length(coalesce(t.doc->'players', '[]'::jsonb)) as seats
      from public.pelham_tee_bookings t
     where t.booking_date = p_date
       and coalesce(t.status, '') <> 'cancelled'
       and (t.hold_expires_at is null or t.hold_expires_at > now())
  )
  select coalesce(jsonb_agg(jsonb_build_object(
           'time', g.label,
           'minutes', g.minutes,
           'rate', public.pelham_tee_rate(p_date),
           'remaining', greatest(4 - coalesce((select sum(d.seats) from day d where d.tee_time = g.label), 0), 0)
         ) order by g.minutes), '[]'::jsonb)
    into result
    from grid g
   where not exists (select 1 from day d where d.tee_time = g.label and d.status = 'blocked')
     and (p_date > local_now::date or (p_date = local_now::date and g.minutes > now_min));

  return jsonb_build_object('date', to_char(p_date, 'YYYY-MM-DD'), 'times', result);
end;
$$;

-- 손님 온라인 예약 한 건. 돌려주는 것은 방금 만든 예약 doc(그 손님 자신의 정보뿐).
-- doc 모양은 `TeeBooking.model_dump(mode="json")` 과 같다 — 어드민 격자가 그대로 읽는다.
create or replace function public.pelham_tee_book(p jsonb)
returns jsonb
language plpgsql
volatile
security definer
set search_path = ''
as $$
declare
  local_now timestamp := public.pelham_local_now();
  v_date date;
  v_time text := btrim(coalesce(p->>'time', ''));
  v_minutes integer;
  v_holes integer;
  v_carts integer;
  v_first text := btrim(coalesce(p->>'firstName', ''));
  v_last text := btrim(coalesce(p->>'lastName', ''));
  v_email text := btrim(coalesce(p->>'email', ''));
  v_phone text := btrim(coalesce(p->>'phone', ''));
  v_notes text := btrim(coalesce(p->>'notes', ''));
  v_party integer;
  v_taken integer;
  v_now text := public.pelham_iso(now());
  v_id text := gen_random_uuid()::text;
  v_players jsonb := '[]'::jsonb;
  v_doc jsonb;
  i integer;
begin
  if coalesce(p->>'date', '') !~ '^\d{4}-\d{2}-\d{2}$' then
    perform public.pelham_fail('422', '''date'' must be an ISO date (YYYY-MM-DD)');
  end if;
  begin
    v_date := (p->>'date')::date;
  exception when others then
    perform public.pelham_fail('422', format('''date'' is not a real calendar date: %s', p->>'date'));
  end;

  select g.m into v_minutes
    from generate_series(6 * 60 + 40, 18 * 60 + 58, 9) as g(m)
   where public.pelham_tee_label(g.m) = v_time;
  if v_minutes is null then
    perform public.pelham_fail('422', format('%s is not a bookable tee time on %s', v_time, p->>'date'));
  end if;
  if v_date < local_now::date
     or (v_date = local_now::date and v_minutes <= extract(hour from local_now) * 60 + extract(minute from local_now)) then
    perform public.pelham_fail('422', 'That tee time has already passed. Please pick a later time.');
  end if;
  if v_date > local_now::date + 365 then
    perform public.pelham_fail('422', 'Online booking opens up to one year ahead.');
  end if;

  v_holes := coalesce(nullif(p->>'holes', ''), '18')::integer;
  if v_holes not in (9, 18) then
    perform public.pelham_fail('422', 'Holes must be 9 or 18.');
  end if;
  v_party := coalesce(nullif(p->>'players', ''), '0')::integer;
  if v_party not between 1 and 4 then
    perform public.pelham_fail('422', 'A tee time holds 1 to 4 players.');
  end if;
  v_carts := coalesce(nullif(p->>'cartCount', ''), '0')::integer;
  if v_carts not between 0 and 4 then
    perform public.pelham_fail('422', 'Carts must be between 0 and 4.');
  end if;
  if v_first = '' and v_last = '' then
    perform public.pelham_fail('422', 'Name is required.');
  end if;
  if v_email = '' or position('@' in v_email) = 0 then
    perform public.pelham_fail('422', 'A valid email is required.');
  end if;
  if length(v_first) + length(v_last) > 120 or length(v_email) > 254
     or length(v_phone) > 40 or length(v_notes) > 1000 then
    perform public.pelham_fail('422', 'Please shorten your name, phone or notes.');
  end if;

  -- 이 티타임의 정원 확인과 기록을 한 잠금 안에서.
  perform pg_advisory_xact_lock(hashtext('pelham_tee:' || v_date::text || ' ' || v_time));

  if exists (
    select 1 from public.pelham_tee_bookings t
     where t.booking_date = v_date and t.tee_time = v_time and t.status = 'blocked'
  ) then
    perform public.pelham_fail('409', format('%s on %s is not available', v_time, p->>'date'));
  end if;

  select coalesce(sum(jsonb_array_length(coalesce(t.doc->'players', '[]'::jsonb))), 0) into v_taken
    from public.pelham_tee_bookings t
   where t.booking_date = v_date
     and t.tee_time = v_time
     and coalesce(t.status, '') <> 'cancelled'
     and (t.hold_expires_at is null or t.hold_expires_at > now());
  if v_taken + v_party > 4 then
    perform public.pelham_fail('409', format(
      '%s on %s only holds 4 players; %s are already taken and %s more were requested',
      v_time, p->>'date', v_taken, v_party));
  end if;

  for i in 1..v_party loop
    v_players := v_players || jsonb_build_object(
      'id', gen_random_uuid()::text,
      'name', case when i = 1 then btrim(v_first || ' ' || v_last) else 'Guest' end,
      'firstName', case when i = 1 then v_first else 'Guest' end,
      'lastName', case when i = 1 then v_last else '' end,
      'email', case when i = 1 then v_email else '' end,
      'phone', case when i = 1 then v_phone else '' end,
      'type', 'Guest',
      'ratePlan', 'Public',
      'arrived', false,
      'paid', false,
      'cancelled', false,
      'no_show', false,
      'cart', false,
      'cartFee', 0.0,
      'paidAt', null
    );
  end loop;

  v_doc := jsonb_build_object(
    'id', v_id,
    'date', to_char(v_date, 'YYYY-MM-DD'),
    'time', v_time,
    'holes', v_holes,
    'rate', public.pelham_tee_rate(v_date),
    'span', 1,
    'color', 'gold',
    'title', btrim(v_first || ' ' || v_last),
    'status', 'reserved',
    'cartCount', v_carts,
    'notes', case when v_notes = '' then 'Booked online at pelhamhills.com.'
                  else v_notes || E'\n\nBooked online at pelhamhills.com.' end,
    'players', v_players,
    'audit', jsonb_build_array(jsonb_build_object(
      'id', gen_random_uuid()::text,
      'ts', v_now,
      'message', format('Reservation created for %s %s.', to_char(v_date, 'YYYY-MM-DD'), v_time)
    )),
    'cancelReason', null,
    'source', 'web',
    'holdExpiresAt', null,
    'createdAt', v_now,
    'updatedAt', v_now
  );

  insert into public.pelham_tee_bookings
    (id, booking_date, tee_time, status, source, title, hold_expires_at, created_at, updated_at, doc, synced_at)
  values
    (v_id, v_date, v_time, 'reserved', 'web', v_doc->>'title', null, now(), now(), v_doc, now());

  return v_doc;
end;
$$;

-- ===== 권한 ============================================================
-- Supabase 는 새 함수를 기본으로 누구에게나 실행하게 둔다. 헬퍼는 막고,
-- 손님용 다섯 개만 연다.

revoke all on function public.pelham_local_now() from public, anon, authenticated;
revoke all on function public.pelham_iso(timestamptz) from public, anon, authenticated;
revoke all on function public.pelham_fail(text, text) from public, anon, authenticated;
revoke all on function public.pelham_tee_label(integer) from public, anon, authenticated;
revoke all on function public.pelham_tee_rate(date) from public, anon, authenticated;

revoke all on function public.pelham_sim_availability(date, text, integer) from public;
revoke all on function public.pelham_sim_reserve(jsonb) from public;
revoke all on function public.pelham_sim_lookup(text) from public;
revoke all on function public.pelham_tee_availability(date) from public;
revoke all on function public.pelham_tee_book(jsonb) from public;

grant execute on function public.pelham_sim_availability(date, text, integer) to anon, authenticated;
grant execute on function public.pelham_sim_reserve(jsonb) to anon, authenticated;
grant execute on function public.pelham_sim_lookup(text) to anon, authenticated;
grant execute on function public.pelham_tee_availability(date) to anon, authenticated;
grant execute on function public.pelham_tee_book(jsonb) to anon, authenticated;
