-- 프로 샵·스낵바 계산대와 **합산 계산서**를 FastAPI 없이 Supabase 에서 돌린다.
--
-- 왜: 리테일 API(`backend/api/routes/retail.py`)는 Fly 서버와 함께 꺼졌다(2026-09-16).
-- 클럽은 2026-09-29 에 두 가지를 정했다.
--   1) 리테일·스낵바를 티 시트처럼 Supabase 로 옮긴다(Fly 는 살리지 않는다).
--   2) 그린피·프로 샵·스낵바를 **계산서 한 장**으로 받는다.
--
-- 모델: 모든 판매는 계산서(`pelham_bills`)다. 공 한 줄을 사 가는 손님도 계산서 한 장이다.
--   - 계산서는 열린 채(open) DB 에 있다. 그래서 티 시트에서 그린피를 담고 리테일 화면으로
--     넘어가 모자를 담아도 같은 계산서가 이어진다(화면 상태가 아니라 DB 상태).
--   - 줄(`pelham_bill_lines`)은 상품(product) 또는 티 시트 플레이어(tee_player)다.
--   - 결제(`pelham_bill_payments`)는 여러 줄이 될 수 있다(분할 결제). 합이 계산서 합계와 같아야 한다.
--   - 결제가 끝나는 순간(한 트랜잭션)에 재고를 깎고, 티 시트 플레이어를 paid 로 바꾸고,
--     영수증 번호를 매긴다. 결제 전에는 아무것도 깎지 않는다("승인 먼저, 기록은 나중").
--
-- 카드: Chase 단말기(Ingenico DX8000)는 아직 앱과 연동되지 않았다(semi-integrated 규격은
-- Chase 에서 받아야 한다). 그때까지 카드·체크카드는 **단말기에서 직접 금액을 치고**, 단말기가
-- 찍어 준 승인번호를 여기 적는다(`entry = 'keyed'`). 승인번호가 없는 카드 결제는 받지 않는다 —
-- "직원 토글만으로 paid 가 되면 안 된다"(2026-09-10 결정). 승인번호·카드 끝 4자리는 단말기가
-- 실제로 준 값만 적는다. 카드 번호·유효기간은 어디에도 저장하지 않는다.
--
-- 규칙 (0004 와 같다)
-- - 공유 프로젝트다. 테이블·함수 전부 `pelham_` 접두사.
-- - 테이블은 RLS 를 켜고 정책을 두지 않는다. 직원이 닿는 문은 `pelham_staff_*` 함수뿐이고,
--   함수마다 `pelham_require_staff()` 가 첫 줄이다.
-- - 금액은 **센트 정수**. 티 시트는 달러 numeric 이라 이 파일에서 한 번만 센트로 바꾼다.
-- - 세금(HST 13%)은 계산서 전체에 **한 번** 매기고 은행가 반올림을 쓴다(파이썬 `round()`,
--   `lib/retail/types.ts` 의 `computeTax` 와 같은 값). Postgres `round()` 는 0.5 를 위로
--   올려서 1센트가 어긋난다.
-- - 오류는 `PTxxx` SQLSTATE. PT404=없음, PT409=상태 충돌, PT422=입력 오류.
--
-- 전제: 0003(`pelham_fail`, `pelham_iso`)과 0004(`pelham_require_staff`, 티 시트 헬퍼)가
-- 먼저 돌아 있어야 한다.
--
-- 실행: SQL editor 에 이 파일 전체를 붙여 한 번. 다시 실행해도 안전하다.

-- ===== 먼저 확인 ======================================================
-- 0003·0004 가 이 프로젝트에 돌아 있어야 한다. 빠진 게 있으면 무엇이 빠졌는지 말하고 멈춘다
-- (중간까지 만들다 깨지는 것보다 낫다).
do $$
declare
  v_missing text[] := '{}';
  v_name text;
begin
  foreach v_name in array array['pelham_fail', 'pelham_iso', 'pelham_local_now', 'pelham_require_staff',
                                 'pelham_tee_audit', 'pelham_tee_save', 'pelham_tee_lock'] loop
    if not exists (select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace
                    where n.nspname = 'public' and p.proname = v_name) then
      v_missing := v_missing || (v_name || '()');
    end if;
  end loop;
  if to_regclass('public.pelham_tee_bookings') is null then
    v_missing := v_missing || 'pelham_tee_bookings'::text;
  end if;
  if cardinality(v_missing) > 0 then
    raise exception '0005 needs 0003 and 0004 first. Missing: %', array_to_string(v_missing, ', ');
  end if;
end;
$$;

-- ===== 테이블 ==========================================================

-- 상품 테이블. 0003 이 만들고 `retail.json` 의 16개 품목을 넣게 되어 있지만, 이 프로젝트에는
-- 그 부분이 빠진 채 0003 이 돌아간 적이 있다(2026-09-29 확인). 그래서 없으면 여기서 같은 모양으로
-- 만들고 같은 16개를 넣는다. 이미 있으면 둘 다 건너뛴다.
create table if not exists public.pelham_retail_products (
  id             integer generated by default as identity primary key,
  sku            text not null unique,
  name           text not null,
  category       text not null,
  price          integer not null check (price >= 0),   -- 센트
  cost           integer not null check (cost >= 0),    -- 센트
  stock          integer,                               -- null = 재고를 세지 않는 대여 품목
  reorder_point  integer not null default 0,
  is_active      boolean not null default true,
  created_at     timestamptz not null default now(),
  updated_at     timestamptz not null default now()
);

-- 시드: 0003 과 같은 16개 품목(`backend/data/retail.json`, 2026-09-08 사본). 비어 있을 때만.
insert into public.pelham_retail_products
  (id, sku, name, category, price, cost, stock, reorder_point, is_active, created_at, updated_at)
select * from (values
  (1, 'PV1-DZ', 'Titleist Pro V1 (Dozen)', 'Balls', 8499, 5900, 48, 12, true, '2026-09-08T07:05:02.744080+00:00'::timestamptz, '2026-09-08T07:05:02.744080+00:00'::timestamptz),
  (2, 'CHRM-DZ', 'Callaway Chrome Soft (Dozen)', 'Balls', 7999, 5500, 36, 12, true, '2026-09-08T07:05:02.744080+00:00', '2026-09-08T07:05:02.744080+00:00'),
  (3, 'TM-QI10-D', 'TaylorMade Qi10 Driver', 'Equipment', 69999, 52000, 4, 2, true, '2026-09-08T07:05:02.744080+00:00', '2026-09-08T07:05:02.744080+00:00'),
  (4, 'VKY-SM10-56', 'Titleist Vokey SM10 Wedge 56', 'Equipment', 24999, 17500, 6, 2, true, '2026-09-08T07:05:02.744080+00:00', '2026-09-08T07:05:02.744080+00:00'),
  (5, 'SC-NP2-34', 'Scotty Cameron Newport 2 Putter (34")', 'Equipment', 64999, 48000, 2, 1, true, '2026-09-08T07:05:02.744080+00:00', '2026-09-08T07:05:02.744080+00:00'),
  (6, 'FJ-POLO-M', 'FootJoy ProDry Polo (M)', 'Apparel', 8999, 4800, 14, 6, true, '2026-09-08T07:05:02.744080+00:00', '2026-09-08T07:05:02.744080+00:00'),
  (7, 'PH-CAP-ADJ', 'Pelham Hills Adjustable Cap', 'Apparel', 3499, 1400, 30, 10, true, '2026-09-08T07:05:02.744080+00:00', '2026-09-08T07:05:02.744080+00:00'),
  (8, 'SM-RAIN-L', 'Sun Mountain Rain Jacket (L)', 'Apparel', 19999, 12000, 5, 3, true, '2026-09-08T07:05:02.744080+00:00', '2026-09-08T07:05:02.744080+00:00'),
  (9, 'FJ-GLV-ML', 'FootJoy WeatherSof Glove (ML)', 'Accessories', 2299, 1150, 40, 12, true, '2026-09-08T07:05:02.744080+00:00', '2026-09-08T07:05:02.744080+00:00'),
  (10, 'TEE-BMB-50', 'Bamboo Tees 2.75" (50 pack)', 'Accessories', 999, 380, 60, 20, true, '2026-09-08T07:05:02.744080+00:00', '2026-09-08T07:05:02.744080+00:00'),
  (11, 'PH-TWL-TRI', 'Pelham Hills Tri-Fold Towel', 'Accessories', 2999, 1300, 18, 6, true, '2026-09-08T07:05:02.744080+00:00', '2026-09-08T07:05:02.744080+00:00'),
  (12, 'DVT-MRK-SET', 'Divot Tool & Ball Marker Set', 'Accessories', 1499, 620, 25, 10, true, '2026-09-08T07:05:02.744080+00:00', '2026-09-08T07:05:02.744080+00:00'),
  (13, 'GTR-591', 'Gatorade 591 mL', 'Food & Beverage', 399, 145, 72, 24, true, '2026-09-08T07:05:02.744080+00:00', '2026-09-08T07:05:02.744080+00:00'),
  (14, 'CLIF-BAR', 'Clif Bar', 'Food & Beverage', 349, 160, 45, 15, true, '2026-09-08T07:05:02.744080+00:00', '2026-09-08T07:05:02.744080+00:00'),
  (15, 'CART-18', 'Power Cart Rental (18 holes)', 'Rentals', 2500, 0, null, 0, true, '2026-09-08T07:05:02.744080+00:00', '2026-09-08T07:05:02.744080+00:00'),
  (16, 'CLUBS-18', 'Rental Clubs (18 holes)', 'Rentals', 4500, 0, null, 0, true, '2026-09-08T07:05:02.744080+00:00', '2026-09-08T07:05:02.744080+00:00')
) as seed (id, sku, name, category, price, cost, stock, reorder_point, is_active, created_at, updated_at)
where not exists (select 1 from public.pelham_retail_products);

-- 상품 테이블은 0003 이 이미 만들고 `retail.json` 의 16개 품목을 넣어 두었다(id 는 정수, 직접 지정).
-- 여기서는 그 테이블을 계산대가 쓸 수 있게 다듬기만 한다: 새 상품의 id 를 DB 가 매기게 하고,
-- 분류를 여섯 개로 묶고, SKU 중복을 대소문자 무시로 막는다.
do $$
begin
  if not exists (select 1 from information_schema.columns
                  where table_schema = 'public' and table_name = 'pelham_retail_products'
                    and column_name = 'id' and is_identity = 'YES') then
    alter table public.pelham_retail_products alter column id add generated by default as identity;
  end if;
  if not exists (select 1 from pg_constraint where conname = 'pelham_retail_products_category_check') then
    alter table public.pelham_retail_products add constraint pelham_retail_products_category_check
      check (category in ('Apparel', 'Equipment', 'Balls', 'Accessories', 'Food & Beverage', 'Rentals'));
  end if;
  if not exists (select 1 from pg_constraint where conname = 'pelham_retail_products_reorder_check') then
    alter table public.pelham_retail_products add constraint pelham_retail_products_reorder_check
      check (reorder_point >= 0);
  end if;
end;
$$;
-- 시드가 id 를 직접 넣었으니 다음 번호를 그 뒤로 옮긴다. 다시 돌려도 같은 결과다.
select setval(pg_get_serial_sequence('public.pelham_retail_products', 'id'),
              greatest((select coalesce(max(id), 0) from public.pelham_retail_products), 1));

-- 재고 이동 원장. 재고 숫자를 바꿀 때마다 한 줄 쌓는다 — "왜 12개가 9개가 됐나"에 답하려고.
-- `pelham_retail_products.stock` 은 이 원장의 합을 들고 있는 사본이고, 같은 트랜잭션에서만 바뀐다.
create table if not exists public.pelham_retail_stock_moves (
  id          bigint generated by default as identity primary key,
  product_id  integer not null references public.pelham_retail_products (id),
  qty_delta   integer not null,
  reason      text not null check (reason in ('initial', 'adjust', 'sale', 'refund')),
  bill_id     bigint,
  note        text,
  created_by  uuid,
  created_at  timestamptz not null default now()
);
create index if not exists pelham_retail_stock_moves_product_idx
  on public.pelham_retail_stock_moves (product_id, created_at);

-- 원장의 출발점: 이미 재고가 있는 상품마다 'initial' 한 줄. 이미 원장이 있는 상품은 건드리지 않는다.
insert into public.pelham_retail_stock_moves (product_id, qty_delta, reason, note)
select p.id, p.stock, 'initial', 'Opening balance (0005)'
  from public.pelham_retail_products p
 where p.stock is not null and p.stock <> 0
   and not exists (select 1 from public.pelham_retail_stock_moves m where m.product_id = p.id);

-- 영수증 번호 `PH-YYYYMMDD-NNNN` 의 날짜별 카운터. `count(*)+1` 로 세면 두 계산대가
-- 동시에 결제할 때 같은 번호가 나온다. 행 잠금으로 하나씩 올린다.
create table if not exists public.pelham_receipt_counters (
  business_date  date primary key,
  last_no        integer not null default 0
);

create table if not exists public.pelham_bills (
  id              bigint generated by default as identity primary key,
  -- 결제 한 번의 멱등 키. 같은 키로 결제가 두 번 오면(더블클릭, 응답 유실 후 재시도)
  -- 두 번째는 첫 번째 결과를 그대로 돌려준다.
  checkout_id     uuid,
  status          text not null default 'open' check (status in ('open', 'paid', 'refunded', 'void')),
  -- 결제할 때 매긴다. 열린 계산서에는 없다.
  receipt_no      text unique,
  -- 매장 현지 날짜(America/Toronto). 결제할 때 정한다.
  business_date   date,
  -- 어디서 열었나(pro_shop / snack_bar / tee_sheet). 마감 리포트를 나눌 때 쓴다.
  station         text not null default 'pro_shop' check (station in ('pro_shop', 'snack_bar', 'tee_sheet')),
  label           text,
  subtotal        integer not null default 0,
  discount        integer not null default 0 check (discount >= 0),
  tax             integer not null default 0,
  total           integer not null default 0,
  -- 팁은 매출이 아니다(직원에게 줄 돈). total 밖에 둔다: net == gross − discount + tax.
  tip             integer not null default 0 check (tip >= 0),
  cashier         text,
  note            text,
  created_by      uuid,
  opened_at       timestamptz not null default now(),
  paid_at         timestamptz,
  refunded_at     timestamptz,
  refund_reason   text,
  voided_at       timestamptz
);
create unique index if not exists pelham_bills_checkout_key
  on public.pelham_bills (checkout_id) where checkout_id is not null;
create index if not exists pelham_bills_status_idx on public.pelham_bills (status);
create index if not exists pelham_bills_date_idx on public.pelham_bills (business_date);

create table if not exists public.pelham_bill_lines (
  id           bigint generated by default as identity primary key,
  bill_id      bigint not null references public.pelham_bills (id) on delete cascade,
  kind         text not null check (kind in ('product', 'tee_player')),
  -- 무효가 된 계산서(환불·취소)의 줄은 false. 아래 "한 사람 한 번" 인덱스가 이 값을 본다.
  active       boolean not null default true,
  product_id   integer references public.pelham_retail_products (id),
  -- 이름·단가는 **담는 시점 값을 복사**한다. 가격을 올려도 지난 영수증이 바뀌지 않게.
  sku          text not null,
  name         text not null,
  category     text not null,
  quantity     integer not null check (quantity > 0),
  unit_price   integer not null check (unit_price >= 0),
  discount     integer not null default 0 check (discount >= 0),
  line_total   integer not null,
  -- tee_player 줄만: 어느 예약의 어느 플레이어인가.
  booking_id   text,
  player_id    text,
  tee_date     date,
  tee_time     text,
  added_at     timestamptz not null default now(),
  check ((kind = 'product') = (product_id is not null)),
  check ((kind = 'tee_player') = (booking_id is not null and player_id is not null))
);
create index if not exists pelham_bill_lines_bill_idx on public.pelham_bill_lines (bill_id);
-- 한 계산서 안에서 같은 상품은 한 줄(수량을 올린다). 두 줄로 나뉘면 재고가 두 번 깎인다.
create unique index if not exists pelham_bill_lines_product_once
  on public.pelham_bill_lines (bill_id, product_id) where kind = 'product';
-- 한 플레이어의 그린피는 살아 있는 계산서 한 곳에만. 두 계산서에 담기면 두 번 받는다.
create unique index if not exists pelham_bill_lines_player_once
  on public.pelham_bill_lines (booking_id, player_id) where kind = 'tee_player' and active;

create table if not exists public.pelham_bill_payments (
  id           bigint generated by default as identity primary key,
  bill_id      bigint not null references public.pelham_bills (id) on delete cascade,
  method       text not null check (method in ('cash', 'card', 'debit', 'member_account', 'gift_card')),
  amount       integer not null check (amount > 0),
  tip          integer not null default 0 check (tip >= 0),
  -- keyed = 단말기에서 직원이 금액을 쳤다(지금). integrated = 앱이 단말기로 보냈다(연동 후).
  -- none = 단말기를 쓰지 않는 수단(현금·회원 계정·기프트 카드).
  entry        text not null check (entry in ('keyed', 'integrated', 'none')),
  auth_code    text check (auth_code is null or length(btrim(auth_code)) between 1 and 32),
  card_last4   text check (card_last4 is null or card_last4 ~ '^[0-9]{4}$'),
  terminal     text,
  created_by   uuid,
  created_at   timestamptz not null default now()
);
create index if not exists pelham_bill_payments_bill_idx on public.pelham_bill_payments (bill_id);

alter table public.pelham_retail_products enable row level security;
alter table public.pelham_retail_stock_moves enable row level security;
alter table public.pelham_receipt_counters enable row level security;
alter table public.pelham_bills enable row level security;
alter table public.pelham_bill_lines enable row level security;
alter table public.pelham_bill_payments enable row level security;

revoke all on public.pelham_retail_products from anon, authenticated;
revoke all on public.pelham_retail_stock_moves from anon, authenticated;
revoke all on public.pelham_receipt_counters from anon, authenticated;
revoke all on public.pelham_bills from anon, authenticated;
revoke all on public.pelham_bill_lines from anon, authenticated;
revoke all on public.pelham_bill_payments from anon, authenticated;

-- ===== 헬퍼 (직원 확인 없음 — 실행 권한을 아무에게도 주지 않는다) ========

-- HST 13%, 은행가 반올림. taxable 850 → 110 (half-up 이면 111). `computeTax` 와 같은 값.
create or replace function public.pelham_pos_tax(p_taxable integer)
returns integer
language plpgsql
immutable
set search_path = ''
as $$
declare
  v_scaled bigint := greatest(coalesce(p_taxable, 0), 0)::bigint * 13;
  v_q bigint := v_scaled / 100;
  v_r bigint := v_scaled % 100;
begin
  if v_r > 50 or (v_r = 50 and v_q % 2 = 1) then
    v_q := v_q + 1;
  end if;
  return v_q::integer;
end;
$$;

-- 매장 현지 날짜(0003 의 `pelham_local_now`, 토론토). 밤 9시에 판 것이 UTC 로 다음 날이 되면 마감이 어긋난다.
create or replace function public.pelham_pos_today()
returns date
language sql
stable
set search_path = ''
as $$
  select public.pelham_local_now()::date
$$;

create or replace function public.pelham_pos_product_json(p public.pelham_retail_products)
returns jsonb
language sql
stable
set search_path = ''
as $$
  select jsonb_build_object(
    'id', p.id,
    'sku', p.sku,
    'name', p.name,
    'category', p.category,
    'price', p.price,
    'cost', p.cost,
    'stock', p.stock,
    'reorder_point', p.reorder_point,
    'is_active', p.is_active,
    'created_at', public.pelham_iso(p.created_at),
    'updated_at', public.pelham_iso(p.updated_at)
  )
$$;

-- 한 플레이어가 내는 그린피(센트). 티 시트 리포트(`pelham_tee_daily_report`)와 같은 규칙:
-- 예약의 rate + (카트를 쓰면) 카트 요금. 둘 다 세전 달러.
create or replace function public.pelham_pos_tee_price(p_doc jsonb, p_player jsonb)
returns integer
language sql
immutable
set search_path = ''
as $$
  select round((coalesce((p_doc->>'rate')::numeric, 0)
                + case when coalesce((p_player->>'cart')::boolean, false)
                       then coalesce((p_player->>'cartFee')::numeric, 0) else 0 end) * 100)::integer
$$;

-- 예약 doc 안에서 플레이어 하나.
create or replace function public.pelham_pos_find_player(p_doc jsonb, p_player text)
returns jsonb
language sql
immutable
set search_path = ''
as $$
  select e.value
    from jsonb_array_elements(coalesce(p_doc->'players', '[]'::jsonb)) as e(value)
   where e.value->>'id' = p_player
   limit 1
$$;

-- 재고 한 번 움직이기: 원장 한 줄 + 상품의 재고 사본. 재고를 세지 않는 품목은 원장만 남기지 않는다.
create or replace function public.pelham_pos_move(
  p_product integer, p_delta integer, p_reason text, p_bill bigint, p_note text
)
returns void
language plpgsql
volatile
set search_path = ''
as $$
declare
  v_stock integer;
begin
  select p.stock into v_stock from public.pelham_retail_products p where p.id = p_product for update;
  if v_stock is null or p_delta = 0 then
    return;
  end if;
  update public.pelham_retail_products
     set stock = stock + p_delta, updated_at = now()
   where id = p_product;
  insert into public.pelham_retail_stock_moves (product_id, qty_delta, reason, bill_id, note, created_by)
  values (p_product, p_delta, p_reason, p_bill, p_note, auth.uid());
end;
$$;

-- 열린 계산서의 금액을 다시 맞춘다. 그린피 줄은 **지금의 예약 doc** 에서 다시 값을 읽는다
-- (담은 뒤에 카트를 붙였으면 따라간다). 결제·취소된 플레이어는 값을 바꾸지 않고 둔다 —
-- 결제 함수가 그 줄을 거절한다.
create or replace function public.pelham_pos_recalc(p_bill bigint)
returns void
language plpgsql
volatile
set search_path = ''
as $$
declare
  l record;
  v_doc jsonb;
  v_player jsonb;
  v_price integer;
  v_subtotal integer;
  v_discount integer;
  v_taxable integer;
  v_status text;
begin
  -- 계산서 행을 먼저 잠근다. 안 잠그면 목록 새로고침의 재계산이 동시에 담긴 상품보다 먼저
  -- 합계를 읽고 나중에 써서, 화면(=직원이 단말기에 치는 금액)이 옛 합계로 돌아간다.
  select b.status into v_status from public.pelham_bills b where b.id = p_bill for update;
  -- 닫힌 계산서(결제·환불·취소)는 건드리지 않는다. 목록을 모은 뒤 그 사이에 닫힌 계산서를
  -- 다시 계산하면, 줄이 모두 무효인 환불 계산서의 합계가 0 으로 덮인다.
  if v_status is distinct from 'open' then
    return;
  end if;
  for l in
    select * from public.pelham_bill_lines where bill_id = p_bill and kind = 'tee_player' and active
  loop
    select t.doc into v_doc from public.pelham_tee_bookings t where t.id = l.booking_id;
    v_player := public.pelham_pos_find_player(v_doc, l.player_id);
    if v_player is null or coalesce((v_player->>'cancelled')::boolean, false)
       or coalesce((v_player->>'paid')::boolean, false) then
      continue;
    end if;
    v_price := public.pelham_pos_tee_price(v_doc, v_player);
    update public.pelham_bill_lines
       set unit_price = v_price,
           line_total = v_price * quantity - least(discount, v_price * quantity),
           name = public.pelham_pos_tee_line_name(v_doc, v_player),
           tee_date = (v_doc->>'date')::date,
           tee_time = v_doc->>'time'
     where id = l.id;
  end loop;

  select coalesce(sum(line_total), 0) into v_subtotal
    from public.pelham_bill_lines where bill_id = p_bill and active;
  select b.discount into v_discount from public.pelham_bills b where b.id = p_bill;
  v_discount := least(coalesce(v_discount, 0), v_subtotal);
  v_taxable := v_subtotal - v_discount;

  update public.pelham_bills
     set subtotal = v_subtotal,
         discount = v_discount,
         tax = public.pelham_pos_tax(v_taxable),
         total = v_taxable + public.pelham_pos_tax(v_taxable)
   where id = p_bill;
end;
$$;

-- 그린피 줄의 이름. 영수증에 그대로 찍힌다: "Green fee — Kestrel, Blake (7:43 AM)".
create or replace function public.pelham_pos_tee_line_name(p_doc jsonb, p_player jsonb)
returns text
language sql
immutable
set search_path = ''
as $$
  select format('%s — %s (%s)',
                case when coalesce((p_player->>'cart')::boolean, false)
                     then 'Green fee + cart' else 'Green fee' end,
                coalesce(nullif(btrim(p_player->>'name'), ''), 'Guest'),
                coalesce(p_doc->>'time', ''))
$$;

-- 계산서 한 장 → 화면이 받는 모양. 결제된 계산서는 기존 `Sale`(lib/retail/types.ts)과
-- 필드 이름이 같다 — 매출 탭과 영수증이 그대로 읽는다. 거기에 lines[].kind, payments[],
-- status, station 이 더 붙는다.
create or replace function public.pelham_pos_bill_json(p_bill bigint)
returns jsonb
language sql
stable
set search_path = ''
as $$
  select jsonb_build_object(
    'id', b.id,
    'status', b.status,
    'station', b.station,
    'label', b.label,
    'receipt_no', b.receipt_no,
    'business_date', to_char(b.business_date, 'YYYY-MM-DD'),
    'checkout_id', b.checkout_id,
    'lines', coalesce((
      select jsonb_agg(jsonb_build_object(
               'id', l.id,
               'kind', l.kind,
               'product_id', l.product_id,
               'sku', l.sku,
               'name', l.name,
               'category', l.category,
               'quantity', l.quantity,
               'unit_price', l.unit_price,
               'discount', l.discount,
               'line_total', l.line_total,
               'booking_id', l.booking_id,
               'player_id', l.player_id,
               'tee_date', to_char(l.tee_date, 'YYYY-MM-DD'),
               'tee_time', l.tee_time
             ) order by l.id)
        from public.pelham_bill_lines l
       where l.bill_id = b.id
         and (l.active or b.status in ('refunded', 'void'))
    ), '[]'::jsonb),
    'payments', coalesce((
      select jsonb_agg(jsonb_build_object(
               'method', p.method,
               'amount', p.amount,
               'tip', p.tip,
               'entry', p.entry,
               'auth_code', p.auth_code,
               'card_last4', p.card_last4,
               'terminal', p.terminal
             ) order by p.id)
        from public.pelham_bill_payments p
       where p.bill_id = b.id
    ), '[]'::jsonb),
    -- 기존 `Sale.payment_method` 자리: 첫 결제 수단. 분할 결제면 payments[] 를 본다.
    'payment_method', (select p.method from public.pelham_bill_payments p
                        where p.bill_id = b.id order by p.id limit 1),
    'subtotal', b.subtotal,
    'discount', b.discount,
    'tax', b.tax,
    'total', b.total,
    'tip', b.tip,
    'cashier', b.cashier,
    'note', b.note,
    'opened_at', public.pelham_iso(b.opened_at),
    'paid_at', public.pelham_iso(b.paid_at),
    'refunded_at', public.pelham_iso(b.refunded_at),
    'refund_reason', b.refund_reason,
    -- `Sale.created_at` 은 영수증 시각이다. 결제된 계산서는 결제 시각을 쓴다.
    'created_at', public.pelham_iso(coalesce(b.paid_at, b.opened_at))
  )
  from public.pelham_bills b
  where b.id = p_bill
$$;

-- 열린 계산서를 잠그고 가져온다. 없거나 이미 닫혔으면 여기서 끝난다.
create or replace function public.pelham_pos_lock_open(p_bill bigint)
returns public.pelham_bills
language plpgsql
volatile
set search_path = ''
as $$
declare
  v public.pelham_bills;
begin
  select * into v from public.pelham_bills where id = p_bill for update;
  if v.id is null then
    perform public.pelham_fail('404', 'Bill not found');
  end if;
  if v.status <> 'open' then
    perform public.pelham_fail('409', format('Bill %s is already %s.', coalesce(v.receipt_no, '#' || v.id), v.status));
  end if;
  return v;
end;
$$;

-- 상품 입력 검증 + 정규화. 생성·수정이 같이 쓴다.
create or replace function public.pelham_pos_check_product(p jsonb)
returns void
language plpgsql
immutable
set search_path = ''
as $$
begin
  if p ? 'category' and (p->>'category') not in
     ('Apparel', 'Equipment', 'Balls', 'Accessories', 'Food & Beverage', 'Rentals') then
    perform public.pelham_fail('422', format('''%s'' is not a product category', p->>'category'));
  end if;
  if p ? 'price' and coalesce((p->>'price')::integer, -1) < 0 then
    perform public.pelham_fail('422', 'Price must be zero or more (cents).');
  end if;
  if p ? 'cost' and coalesce((p->>'cost')::integer, 0) < 0 then
    perform public.pelham_fail('422', 'Cost cannot be negative.');
  end if;
  if p ? 'stock' and jsonb_typeof(p->'stock') <> 'null' and (p->>'stock')::integer < 0 then
    perform public.pelham_fail('422', 'Stock cannot be negative. Leave it empty for rentals.');
  end if;
  if p ? 'sku' and length(btrim(coalesce(p->>'sku', ''))) not between 1 and 64 then
    perform public.pelham_fail('422', 'SKU must be 1–64 characters.');
  end if;
  if p ? 'name' and length(btrim(coalesce(p->>'name', ''))) not between 1 and 120 then
    perform public.pelham_fail('422', 'Name must be 1–120 characters.');
  end if;
end;
$$;

-- ===== 티 시트 보호 ====================================================
-- 계산서로 받은 그린피를 티 시트에서 "Mark unpaid" 하거나, 그 플레이어·예약을 지우면
-- 계산서(돈을 받았다)와 티 시트(안 받았다)가 갈라진다. 그 길은 계산서 환불 하나로만 연다.
create or replace function public.pelham_pos_guard_tee()
returns trigger
language plpgsql
set search_path = ''
as $$
declare
  l record;
  v_player jsonb;
begin
  for l in
    select li.player_id, li.name, b.receipt_no
      from public.pelham_bill_lines li
      join public.pelham_bills b on b.id = li.bill_id
     where li.booking_id = old.id
       and li.kind = 'tee_player'
       and li.active
       and b.status = 'paid'
  loop
    if tg_op = 'DELETE' then
      perform public.pelham_fail('409', format(
        'This reservation was paid on bill %s. Refund that bill before deleting it.', l.receipt_no));
    end if;
    v_player := public.pelham_pos_find_player(new.doc, l.player_id);
    if v_player is null or not coalesce((v_player->>'paid')::boolean, false) then
      perform public.pelham_fail('409', format(
        '%s was paid on bill %s. Refund that bill instead of clearing the payment or removing the player.',
        l.name, l.receipt_no));
    end if;
  end loop;
  if tg_op = 'DELETE' then
    return old;
  end if;
  return new;
end;
$$;

drop trigger if exists pelham_pos_guard_tee on public.pelham_tee_bookings;
create trigger pelham_pos_guard_tee
  before update or delete on public.pelham_tee_bookings
  for each row execute function public.pelham_pos_guard_tee();

-- ===== 직원 함수 · 상품 ================================================

create or replace function public.pelham_staff_pos_products(p_active boolean default null)
returns jsonb
language plpgsql
stable
security definer
set search_path = ''
as $$
begin
  perform public.pelham_require_staff();
  return coalesce((
    select jsonb_agg(public.pelham_pos_product_json(p) order by p.category, p.name, p.id)
      from public.pelham_retail_products p
     where p_active is null or p.is_active = p_active
  ), '[]'::jsonb);
end;
$$;

create or replace function public.pelham_staff_pos_product_create(p jsonb)
returns jsonb
language plpgsql
volatile
security definer
set search_path = ''
as $$
declare
  v public.pelham_retail_products;
  v_stock integer;
begin
  perform public.pelham_require_staff();
  p := coalesce(p, '{}'::jsonb);
  if not (p ? 'sku' and p ? 'name' and p ? 'category' and p ? 'price') then
    perform public.pelham_fail('422', 'sku, name, category and price are required.');
  end if;
  perform public.pelham_pos_check_product(p);
  if exists (select 1 from public.pelham_retail_products
              where lower(btrim(sku)) = lower(btrim(p->>'sku'))) then
    perform public.pelham_fail('409', format('SKU %s already exists.', btrim(p->>'sku')));
  end if;

  v_stock := case when jsonb_typeof(p->'stock') in ('number', 'string') then (p->>'stock')::integer end;
  insert into public.pelham_retail_products (sku, name, category, price, cost, stock, reorder_point, is_active)
  values (btrim(p->>'sku'), btrim(p->>'name'), p->>'category', (p->>'price')::integer,
          coalesce((p->>'cost')::integer, 0),
          -- 원장의 출발점은 아래 'initial' 이동이다. 여기서는 0(또는 null)으로 넣는다.
          case when v_stock is null then null else 0 end,
          coalesce((p->>'reorder_point')::integer, 0),
          coalesce((p->>'is_active')::boolean, true))
  returning * into v;

  if v_stock is not null and v_stock <> 0 then
    perform public.pelham_pos_move(v.id, v_stock, 'initial', null, 'Stock when the product was added');
  end if;
  select * into v from public.pelham_retail_products where id = v.id;
  return public.pelham_pos_product_json(v);
end;
$$;

-- 부분 수정. 보낸 필드만 바뀐다. stock 을 보내면 차이만큼 'adjust' 이동이 쌓인다.
create or replace function public.pelham_staff_pos_product_update(p_id integer, p jsonb)
returns jsonb
language plpgsql
volatile
security definer
set search_path = ''
as $$
declare
  v public.pelham_retail_products;
  v_new_stock integer;
begin
  perform public.pelham_require_staff();
  p := coalesce(p, '{}'::jsonb);
  perform public.pelham_pos_check_product(p);

  select * into v from public.pelham_retail_products where id = p_id for update;
  if v.id is null then
    perform public.pelham_fail('404', 'Product not found');
  end if;
  if p ? 'sku' and exists (select 1 from public.pelham_retail_products
                            where lower(btrim(sku)) = lower(btrim(p->>'sku')) and id <> p_id) then
    perform public.pelham_fail('409', format('SKU %s already exists.', btrim(p->>'sku')));
  end if;

  update public.pelham_retail_products
     set sku = case when p ? 'sku' then btrim(p->>'sku') else sku end,
         name = case when p ? 'name' then btrim(p->>'name') else name end,
         category = coalesce(p->>'category', category),
         price = coalesce((p->>'price')::integer, price),
         cost = coalesce((p->>'cost')::integer, cost),
         reorder_point = coalesce((p->>'reorder_point')::integer, reorder_point),
         is_active = coalesce((p->>'is_active')::boolean, is_active),
         updated_at = now()
   where id = p_id;

  if p ? 'stock' then
    if jsonb_typeof(p->'stock') = 'null' then
      -- 재고 추적을 끈다(렌탈로 바꿈). 원장은 남는다.
      update public.pelham_retail_products set stock = null, updated_at = now() where id = p_id;
    else
      v_new_stock := (p->>'stock')::integer;
      if v.stock is null then
        -- 추적을 새로 켠다. 0 에서 출발해 'initial' 로 채운다.
        update public.pelham_retail_products set stock = 0 where id = p_id;
        perform public.pelham_pos_move(p_id, v_new_stock, 'initial', null, 'Stock tracking turned on');
      else
        perform public.pelham_pos_move(p_id, v_new_stock - v.stock, 'adjust', null, 'Edited on the Products tab');
      end if;
    end if;
  end if;

  select * into v from public.pelham_retail_products where id = p_id;
  return public.pelham_pos_product_json(v);
end;
$$;

create or replace function public.pelham_staff_pos_product_deactivate(p_id integer)
returns jsonb
language plpgsql
volatile
security definer
set search_path = ''
as $$
declare
  v public.pelham_retail_products;
begin
  perform public.pelham_require_staff();
  update public.pelham_retail_products set is_active = false, updated_at = now()
   where id = p_id returning * into v;
  if v.id is null then
    perform public.pelham_fail('404', 'Product not found');
  end if;
  return public.pelham_pos_product_json(v);
end;
$$;

-- 발주가 필요한 품목. 렌탈(stock null)과 비활성 상품은 뺀다(`retail.py` 와 같다).
create or replace function public.pelham_staff_pos_low_stock()
returns jsonb
language plpgsql
stable
security definer
set search_path = ''
as $$
begin
  perform public.pelham_require_staff();
  return coalesce((
    select jsonb_agg(jsonb_build_object(
             'product_id', p.id, 'sku', p.sku, 'name', p.name, 'category', p.category,
             'stock', p.stock, 'reorder_point', p.reorder_point
           ) order by p.stock, p.id)
      from public.pelham_retail_products p
     where p.stock is not null and p.is_active and p.stock <= p.reorder_point
  ), '[]'::jsonb);
end;
$$;

-- ===== 직원 함수 · 계산서 ==============================================

-- 새 계산서. p: {station, label, cashier, note}
create or replace function public.pelham_staff_bill_open(p jsonb default '{}'::jsonb)
returns jsonb
language plpgsql
volatile
security definer
set search_path = ''
as $$
declare
  v_id bigint;
  v_station text := coalesce(nullif(p->>'station', ''), 'pro_shop');
begin
  perform public.pelham_require_staff();
  if v_station not in ('pro_shop', 'snack_bar', 'tee_sheet') then
    perform public.pelham_fail('422', format('''%s'' is not a station', v_station));
  end if;
  insert into public.pelham_bills (station, label, cashier, note, created_by)
  values (v_station, nullif(btrim(coalesce(p->>'label', '')), ''),
          nullif(btrim(coalesce(p->>'cashier', '')), ''),
          nullif(btrim(coalesce(p->>'note', '')), ''), auth.uid())
  returning id into v_id;
  return public.pelham_pos_bill_json(v_id);
end;
$$;

-- 열린 계산서 전부(오래된 것부터). 카운터의 "열린 계산서" 목록.
create or replace function public.pelham_staff_bills_open()
returns jsonb
language plpgsql
volatile
security definer
set search_path = ''
as $$
declare
  v_id bigint;
begin
  perform public.pelham_require_staff();
  -- 목록을 그리기 전에 그린피를 지금 값으로 맞춘다(담은 뒤 카트를 붙였을 수 있다).
  -- id 순으로 잠근다. 두 계산대가 서로 다른 순서로 잠그면 교착(deadlock)이 난다.
  for v_id in select id from public.pelham_bills where status = 'open' order by id loop
    perform public.pelham_pos_recalc(v_id);
  end loop;
  return coalesce((
    select jsonb_agg(public.pelham_pos_bill_json(b.id) order by b.opened_at, b.id)
      from public.pelham_bills b where b.status = 'open'
  ), '[]'::jsonb);
end;
$$;

create or replace function public.pelham_staff_bill(p_id bigint)
returns jsonb
language plpgsql
volatile
security definer
set search_path = ''
as $$
declare
  v_status text;
begin
  perform public.pelham_require_staff();
  select status into v_status from public.pelham_bills where id = p_id;
  if v_status is null then
    perform public.pelham_fail('404', 'Bill not found');
  end if;
  if v_status = 'open' then
    perform public.pelham_pos_recalc(p_id);
  end if;
  return public.pelham_pos_bill_json(p_id);
end;
$$;

-- 상품 담기. 같은 상품이 이미 있으면 수량을 더한다(스캔 두 번 = 2개).
create or replace function public.pelham_staff_bill_add_product(p_bill bigint, p_product integer, p_quantity integer default 1)
returns jsonb
language plpgsql
volatile
security definer
set search_path = ''
as $$
declare
  v_product public.pelham_retail_products;
begin
  perform public.pelham_require_staff();
  perform public.pelham_pos_lock_open(p_bill);
  if coalesce(p_quantity, 0) < 1 or p_quantity > 9999 then
    perform public.pelham_fail('422', 'Quantity must be between 1 and 9999.');
  end if;
  select * into v_product from public.pelham_retail_products where id = p_product;
  if v_product.id is null then
    perform public.pelham_fail('404', 'Product not found');
  end if;
  if not v_product.is_active then
    perform public.pelham_fail('409', format('%s (%s) is not for sale.', v_product.name, v_product.sku));
  end if;

  insert into public.pelham_bill_lines (bill_id, kind, product_id, sku, name, category, quantity, unit_price, line_total)
  values (p_bill, 'product', v_product.id, v_product.sku, v_product.name, v_product.category,
          p_quantity, v_product.price, p_quantity * v_product.price)
  on conflict (bill_id, product_id) where kind = 'product'
  do update set quantity = public.pelham_bill_lines.quantity + excluded.quantity,
                line_total = (public.pelham_bill_lines.quantity + excluded.quantity) * public.pelham_bill_lines.unit_price
                             - least(public.pelham_bill_lines.discount,
                                     (public.pelham_bill_lines.quantity + excluded.quantity) * public.pelham_bill_lines.unit_price);

  perform public.pelham_pos_recalc(p_bill);
  return public.pelham_pos_bill_json(p_bill);
end;
$$;

-- 줄 하나 고치기. p: {quantity, discount}. quantity 0 이면 줄을 지운다.
-- 그린피 줄은 수량을 바꿀 수 없다(한 사람 = 한 줄). 할인만 된다.
create or replace function public.pelham_staff_bill_line_update(p_bill bigint, p_line bigint, p jsonb)
returns jsonb
language plpgsql
volatile
security definer
set search_path = ''
as $$
declare
  l public.pelham_bill_lines;
  v_qty integer;
  v_discount integer;
begin
  perform public.pelham_require_staff();
  perform public.pelham_pos_lock_open(p_bill);
  select * into l from public.pelham_bill_lines where id = p_line and bill_id = p_bill;
  if l.id is null then
    perform public.pelham_fail('404', 'Line not found on this bill');
  end if;
  p := coalesce(p, '{}'::jsonb);

  v_qty := coalesce((p->>'quantity')::integer, l.quantity);
  if l.kind = 'tee_player' and v_qty not in (0, 1) then
    perform public.pelham_fail('422', 'A green fee line is one player. Remove it or keep it.');
  end if;
  if v_qty = 0 then
    delete from public.pelham_bill_lines where id = p_line;
  else
    if v_qty < 0 or v_qty > 9999 then
      perform public.pelham_fail('422', 'Quantity must be between 0 and 9999.');
    end if;
    v_discount := coalesce((p->>'discount')::integer, l.discount);
    if v_discount < 0 then
      perform public.pelham_fail('422', 'Discount cannot be negative.');
    end if;
    -- 줄 할인은 줄 합계를 넘지 못한다. 넘으면 잘라 둔다(화면도 같은 값을 보여 준다).
    v_discount := least(v_discount, v_qty * l.unit_price);
    update public.pelham_bill_lines
       set quantity = v_qty, discount = v_discount, line_total = v_qty * unit_price - v_discount
     where id = p_line;
  end if;

  perform public.pelham_pos_recalc(p_bill);
  return public.pelham_pos_bill_json(p_bill);
end;
$$;

-- 계산서 머리 고치기. p: {discount, cashier, note, label}
create or replace function public.pelham_staff_bill_update(p_bill bigint, p jsonb)
returns jsonb
language plpgsql
volatile
security definer
set search_path = ''
as $$
begin
  perform public.pelham_require_staff();
  perform public.pelham_pos_lock_open(p_bill);
  p := coalesce(p, '{}'::jsonb);
  if p ? 'discount' and coalesce((p->>'discount')::integer, -1) < 0 then
    perform public.pelham_fail('422', 'Discount must be zero or more (cents).');
  end if;
  update public.pelham_bills
     set discount = coalesce((p->>'discount')::integer, discount),
         cashier = case when p ? 'cashier' then nullif(btrim(coalesce(p->>'cashier', '')), '') else cashier end,
         note = case when p ? 'note' then nullif(btrim(coalesce(p->>'note', '')), '') else note end,
         label = case when p ? 'label' then nullif(btrim(coalesce(p->>'label', '')), '') else label end
   where id = p_bill;
  perform public.pelham_pos_recalc(p_bill);
  return public.pelham_pos_bill_json(p_bill);
end;
$$;

-- 티 시트 플레이어의 그린피를 담는다. p_players 가 비어 있으면 그 예약에서 아직 안 낸 사람 전부.
-- 이미 낸 사람·취소된 사람은 건너뛰지 않고 거절한다 — 직원이 "넷 다 담겼다"고 믿으면 안 된다.
create or replace function public.pelham_staff_bill_add_tee(p_bill bigint, p_booking text, p_players text[] default null)
returns jsonb
language plpgsql
volatile
security definer
set search_path = ''
as $$
declare
  v_doc jsonb;
  v_player jsonb;
  v_ids text[];
  v_id text;
  v_other text;
  v_price integer;
begin
  perform public.pelham_require_staff();
  perform public.pelham_pos_lock_open(p_bill);

  select t.doc into v_doc from public.pelham_tee_bookings t where t.id = p_booking;
  if v_doc is null then
    perform public.pelham_fail('404', 'Booking not found');
  end if;

  if p_players is null or cardinality(p_players) = 0 then
    select coalesce(array_agg(e.value->>'id' order by e.ord), '{}')
      into v_ids
      from jsonb_array_elements(coalesce(v_doc->'players', '[]'::jsonb)) with ordinality as e(value, ord)
     where not coalesce((e.value->>'paid')::boolean, false)
       and not coalesce((e.value->>'cancelled')::boolean, false)
       and not exists (select 1 from public.pelham_bill_lines li
                        where li.booking_id = p_booking and li.player_id = e.value->>'id'
                          and li.kind = 'tee_player' and li.active);
    if cardinality(v_ids) = 0 then
      perform public.pelham_fail('409', 'Everyone on this reservation has paid or is already on a bill.');
    end if;
  else
    v_ids := p_players;
  end if;

  foreach v_id in array v_ids loop
    v_player := public.pelham_pos_find_player(v_doc, v_id);
    if v_player is null then
      perform public.pelham_fail('404', 'Player not found on this reservation');
    end if;
    if coalesce((v_player->>'cancelled')::boolean, false) then
      perform public.pelham_fail('409', format('%s is cancelled.', coalesce(v_player->>'name', 'This player')));
    end if;
    if coalesce((v_player->>'paid')::boolean, false) then
      perform public.pelham_fail('409', format('%s has already paid.', coalesce(v_player->>'name', 'This player')));
    end if;
    select coalesce(b.receipt_no, b.label, '#' || b.id) into v_other
      from public.pelham_bill_lines li join public.pelham_bills b on b.id = li.bill_id
     where li.booking_id = p_booking and li.player_id = v_id and li.kind = 'tee_player' and li.active
     limit 1;
    if v_other is not null then
      perform public.pelham_fail('409', format('%s is already on bill %s.',
                                               coalesce(v_player->>'name', 'This player'), v_other));
    end if;

    v_price := public.pelham_pos_tee_price(v_doc, v_player);
    insert into public.pelham_bill_lines
      (bill_id, kind, sku, name, category, quantity, unit_price, line_total,
       booking_id, player_id, tee_date, tee_time)
    values
      (p_bill, 'tee_player', 'TEE', public.pelham_pos_tee_line_name(v_doc, v_player), 'Green Fees',
       1, v_price, v_price, p_booking, v_id, (v_doc->>'date')::date, v_doc->>'time');
  end loop;

  perform public.pelham_pos_recalc(p_bill);
  return public.pelham_pos_bill_json(p_bill);
end;
$$;

-- 열린 계산서 버리기. 돈이 오가지 않았으니 되돌릴 것이 없다. 줄은 남기되 무효로 한다.
create or replace function public.pelham_staff_bill_void(p_bill bigint)
returns jsonb
language plpgsql
volatile
security definer
set search_path = ''
as $$
begin
  perform public.pelham_require_staff();
  perform public.pelham_pos_lock_open(p_bill);
  update public.pelham_bill_lines set active = false where bill_id = p_bill;
  update public.pelham_bills set status = 'void', voided_at = now() where id = p_bill;
  return public.pelham_pos_bill_json(p_bill);
end;
$$;

-- 결제. 한 트랜잭션 안에서: 금액 재계산 → 결제 검증 → 재고 차감 → 티 시트 paid → 영수증 번호.
-- p: {checkout_id, payments: [{method, amount, tip?, auth_code?, card_last4?}]}
create or replace function public.pelham_staff_bill_pay(p_bill bigint, p jsonb)
returns jsonb
language plpgsql
volatile
security definer
set search_path = ''
as $$
declare
  v_bill public.pelham_bills;
  v_checkout uuid;
  v_payments jsonb := coalesce(p->'payments', '[]'::jsonb);
  pay jsonb;
  v_method text;
  v_amount integer;
  v_sum integer := 0;
  v_tips integer := 0;
  l record;
  v_doc jsonb;
  v_player jsonb;
  v_players jsonb;
  v_now text := public.pelham_iso(now());
  v_date date := public.pelham_pos_today();
  v_no integer;
  v_receipt text;
  v_booking text;
  v_names text[];
  v_stock integer;
  v_active boolean;
begin
  perform public.pelham_require_staff();
  p := coalesce(p, '{}'::jsonb);

  begin
    v_checkout := nullif(p->>'checkout_id', '')::uuid;
  exception when others then
    perform public.pelham_fail('422', 'checkout_id must be a UUID.');
  end;
  if v_checkout is null then
    perform public.pelham_fail('422', 'checkout_id is required (one per Charge press).');
  end if;

  -- 계산서를 먼저 잠그고 나서 멱등 키를 본다. 거꾸로 하면 동시에 온 재시도 두 개 중
  -- 뒤의 것이 "이미 결제됨" 오류를 받는다 — 돈은 받았는데 계산대에 빨간 오류가 뜬다.
  select * into v_bill from public.pelham_bills where id = p_bill for update;
  if v_bill.id is null then
    perform public.pelham_fail('404', 'Bill not found');
  end if;
  -- 같은 결제가 두 번 왔다(응답이 끊겨 화면이 다시 보냄). 첫 결과를 그대로 돌려준다.
  if v_bill.checkout_id = v_checkout then
    return public.pelham_pos_bill_json(v_bill.id);
  end if;
  if exists (select 1 from public.pelham_bills where checkout_id = v_checkout and id <> p_bill) then
    perform public.pelham_fail('409', 'This checkout_id belongs to another bill.');
  end if;

  v_bill := public.pelham_pos_lock_open(p_bill);
  if not exists (select 1 from public.pelham_bill_lines where bill_id = p_bill and active) then
    perform public.pelham_fail('422', 'The bill is empty.');
  end if;

  -- 1) 그린피 줄: 예약마다 잠그고, 플레이어가 아직 낼 수 있는 상태인지 본다.
  for v_booking in
    select distinct li.booking_id from public.pelham_bill_lines li
     where li.bill_id = p_bill and li.kind = 'tee_player' and li.active
     order by 1
  loop
    select t.doc into v_doc from public.pelham_tee_bookings t where t.id = v_booking;
    if v_doc is null then
      perform public.pelham_fail('409', 'A reservation on this bill no longer exists. Remove its line.');
    end if;
    perform public.pelham_tee_lock((v_doc->>'date')::date, v_doc->>'time');
    select t.doc into v_doc from public.pelham_tee_bookings t where t.id = v_booking for update;
    for l in select * from public.pelham_bill_lines li
              where li.bill_id = p_bill and li.booking_id = v_booking and li.kind = 'tee_player' and li.active loop
      v_player := public.pelham_pos_find_player(v_doc, l.player_id);
      if v_player is null then
        perform public.pelham_fail('409', format('%s was removed from the reservation. Remove the line.', l.name));
      end if;
      if coalesce((v_player->>'cancelled')::boolean, false) then
        perform public.pelham_fail('409', format('%s is cancelled. Remove the line.', l.name));
      end if;
      if coalesce((v_player->>'paid')::boolean, false) then
        perform public.pelham_fail('409', format('%s was already marked paid on the tee sheet. Remove the line.', l.name));
      end if;
    end loop;
  end loop;

  perform public.pelham_pos_recalc(p_bill);
  select * into v_bill from public.pelham_bills where id = p_bill;

  -- 2) 결제 검증. 합이 계산서 합계와 같아야 한다(거스름돈은 화면이 계산한다).
  if jsonb_typeof(v_payments) <> 'array' then
    perform public.pelham_fail('422', 'payments must be a list.');
  end if;
  for pay in select value from jsonb_array_elements(v_payments) loop
    v_method := pay->>'method';
    if v_method is null or v_method not in ('cash', 'card', 'debit', 'member_account', 'gift_card') then
      perform public.pelham_fail('422', format('''%s'' is not a payment method', coalesce(v_method, '')));
    end if;
    v_amount := coalesce((pay->>'amount')::integer, 0);
    if v_amount <= 0 then
      perform public.pelham_fail('422', 'Each payment needs an amount above zero (cents).');
    end if;
    if coalesce((pay->>'tip')::integer, 0) < 0 then
      perform public.pelham_fail('422', 'Tip cannot be negative.');
    end if;
    if v_method in ('card', 'debit') and length(btrim(coalesce(pay->>'auth_code', ''))) = 0 then
      perform public.pelham_fail('422',
        'Card and debit payments need the approval code printed by the Chase terminal.');
    end if;
    if nullif(pay->>'card_last4', '') is not null and (pay->>'card_last4') !~ '^[0-9]{4}$' then
      perform public.pelham_fail('422', 'Card last 4 must be four digits.');
    end if;
    v_sum := v_sum + v_amount;
    v_tips := v_tips + coalesce((pay->>'tip')::integer, 0);
  end loop;
  if v_sum <> v_bill.total then
    perform public.pelham_fail('422', format('Payments add up to %s but the bill total is %s (cents).',
                                             v_sum, v_bill.total));
  end if;

  -- 3) 재고. 상품 id 순으로 잠가 두 계산대가 서로를 기다리다 멈추지 않게 한다.
  for l in
    select li.product_id, sum(li.quantity)::integer as qty, min(li.name) as name
      from public.pelham_bill_lines li
     where li.bill_id = p_bill and li.kind = 'product' and li.active
     group by li.product_id order by li.product_id
  loop
    select p2.stock, p2.is_active into v_stock, v_active
      from public.pelham_retail_products p2 where p2.id = l.product_id for update;
    if not v_active then
      perform public.pelham_fail('409', format('%s is no longer for sale. Remove the line.', l.name));
    end if;
    if v_stock is not null and v_stock < l.qty then
      perform public.pelham_fail('409', format('Not enough stock: %s (need %s, %s on hand).', l.name, l.qty, v_stock));
    end if;
  end loop;

  -- 4) 영수증 번호.
  insert into public.pelham_receipt_counters as c (business_date, last_no) values (v_date, 1)
  on conflict (business_date) do update set last_no = c.last_no + 1
  returning last_no into v_no;
  v_receipt := format('PH-%s-%s', to_char(v_date, 'YYYYMMDD'), lpad(v_no::text, 4, '0'));

  -- 5) 기록. 여기부터는 실패할 이유가 없다.
  for l in
    select li.product_id, sum(li.quantity)::integer as qty
      from public.pelham_bill_lines li
     where li.bill_id = p_bill and li.kind = 'product' and li.active
     group by li.product_id order by li.product_id
  loop
    perform public.pelham_pos_move(l.product_id, -l.qty, 'sale', p_bill, v_receipt);
  end loop;

  for pay in select value from jsonb_array_elements(v_payments) loop
    v_method := pay->>'method';
    insert into public.pelham_bill_payments (bill_id, method, amount, tip, entry, auth_code, card_last4, terminal, created_by)
    values (p_bill, v_method, (pay->>'amount')::integer, coalesce((pay->>'tip')::integer, 0),
            case when v_method in ('card', 'debit') then 'keyed' else 'none' end,
            nullif(btrim(coalesce(pay->>'auth_code', '')), ''),
            nullif(pay->>'card_last4', ''),
            case when v_method in ('card', 'debit') then 'Chase DX8000' end,
            auth.uid());
  end loop;

  update public.pelham_bills
     set status = 'paid', checkout_id = v_checkout, receipt_no = v_receipt, business_date = v_date,
         tip = v_tips, paid_at = now()
   where id = p_bill;

  -- 티 시트: 계산서에 담긴 사람만 paid. 결제 시각은 서버가 찍는다(0004 와 같다).
  for v_booking in
    select distinct li.booking_id from public.pelham_bill_lines li
     where li.bill_id = p_bill and li.kind = 'tee_player' and li.active
  loop
    select t.doc into v_doc from public.pelham_tee_bookings t where t.id = v_booking;
    select coalesce(jsonb_agg(
             case when exists (select 1 from public.pelham_bill_lines li
                                where li.bill_id = p_bill and li.booking_id = v_booking
                                  and li.player_id = e.value->>'id' and li.kind = 'tee_player' and li.active)
                  then e.value || jsonb_build_object('paid', true, 'paidAt', v_now)
                  else e.value end
             order by e.ord), '[]'::jsonb)
      into v_players
      from jsonb_array_elements(coalesce(v_doc->'players', '[]'::jsonb)) with ordinality as e(value, ord);
    select array_agg(li.name order by li.id) into v_names
      from public.pelham_bill_lines li
     where li.bill_id = p_bill and li.booking_id = v_booking and li.kind = 'tee_player' and li.active;
    v_doc := jsonb_set(v_doc, '{players}', v_players);
    v_doc := public.pelham_tee_audit(v_doc,
               format('Paid on bill %s: %s.', v_receipt, array_to_string(v_names, ', ')), v_now);
    perform public.pelham_tee_save(v_doc);
  end loop;

  return public.pelham_pos_bill_json(p_bill);
end;
$$;

-- 환불. 카드·체크카드는 **Chase 단말기에서 먼저 환불**한 뒤 이 함수를 부른다(화면이 안내한다).
-- 계산서를 지우지 않는다: 상태만 refunded 로 두고 재고를 되돌리고 그린피를 미결제로 돌린다.
create or replace function public.pelham_staff_bill_refund(p_bill bigint, p_reason text)
returns jsonb
language plpgsql
volatile
security definer
set search_path = ''
as $$
declare
  v_bill public.pelham_bills;
  l record;
  v_booking text;
  v_doc jsonb;
  v_players jsonb;
  v_now text := public.pelham_iso(now());
  v_ids text[];
begin
  perform public.pelham_require_staff();
  if length(btrim(coalesce(p_reason, ''))) = 0 then
    perform public.pelham_fail('422', 'Give a reason for the refund.');
  end if;
  select * into v_bill from public.pelham_bills where id = p_bill for update;
  if v_bill.id is null then
    perform public.pelham_fail('404', 'Bill not found');
  end if;
  if v_bill.status <> 'paid' then
    perform public.pelham_fail('409', format('Only a paid bill can be refunded (this one is %s).', v_bill.status));
  end if;

  -- 줄을 먼저 무효로 한다. 그래야 아래 티 시트 되돌리기가 보호 트리거에 걸리지 않는다.
  select coalesce(array_agg(distinct li.booking_id), '{}') into v_ids
    from public.pelham_bill_lines li where li.bill_id = p_bill and li.kind = 'tee_player' and li.active;
  update public.pelham_bills
     set status = 'refunded', refunded_at = now(), refund_reason = btrim(p_reason)
   where id = p_bill;

  for l in
    select li.product_id, sum(li.quantity)::integer as qty
      from public.pelham_bill_lines li
     where li.bill_id = p_bill and li.kind = 'product' and li.active
     group by li.product_id order by li.product_id
  loop
    perform public.pelham_pos_move(l.product_id, l.qty, 'refund', p_bill, v_bill.receipt_no);
  end loop;

  foreach v_booking in array v_ids loop
    select t.doc into v_doc from public.pelham_tee_bookings t where t.id = v_booking;
    if v_doc is null then
      continue; -- 예약이 없어졌다(보호 트리거 이전의 기록). 돌려놓을 곳이 없다.
    end if;
    perform public.pelham_tee_lock((v_doc->>'date')::date, v_doc->>'time');
    select t.doc into v_doc from public.pelham_tee_bookings t where t.id = v_booking for update;
    select coalesce(jsonb_agg(
             case when exists (select 1 from public.pelham_bill_lines li
                                where li.bill_id = p_bill and li.booking_id = v_booking
                                  and li.player_id = e.value->>'id' and li.kind = 'tee_player' and li.active)
                  then e.value || jsonb_build_object('paid', false, 'paidAt', null)
                  else e.value end
             order by e.ord), '[]'::jsonb)
      into v_players
      from jsonb_array_elements(coalesce(v_doc->'players', '[]'::jsonb)) with ordinality as e(value, ord);
    update public.pelham_bill_lines set active = false
     where bill_id = p_bill and booking_id = v_booking and kind = 'tee_player';
    v_doc := jsonb_set(v_doc, '{players}', v_players);
    v_doc := public.pelham_tee_audit(v_doc, format('Refunded bill %s: %s.', v_bill.receipt_no, btrim(p_reason)), v_now);
    perform public.pelham_tee_save(v_doc);
  end loop;

  update public.pelham_bill_lines set active = false where bill_id = p_bill;
  return public.pelham_pos_bill_json(p_bill);
end;
$$;

-- 한 영업일의 결제된·환불된 계산서(최신순). 매출 탭이 읽는다.
create or replace function public.pelham_staff_bills(p_date date)
returns jsonb
language plpgsql
stable
security definer
set search_path = ''
as $$
begin
  perform public.pelham_require_staff();
  return coalesce((
    select jsonb_agg(public.pelham_pos_bill_json(b.id) order by b.paid_at desc, b.id desc)
      from public.pelham_bills b
     where b.business_date = p_date and b.status in ('paid', 'refunded')
  ), '[]'::jsonb);
end;
$$;

-- 영수증 번호로 찾기(스캐너로 영수증을 찍었을 때).
create or replace function public.pelham_staff_bill_by_receipt(p_receipt text)
returns jsonb
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
  v_id bigint;
begin
  perform public.pelham_require_staff();
  select id into v_id from public.pelham_bills where upper(receipt_no) = upper(btrim(coalesce(p_receipt, '')));
  if v_id is null then
    perform public.pelham_fail('404', format('No bill with receipt %s', coalesce(p_receipt, '')));
  end if;
  return public.pelham_pos_bill_json(v_id);
end;
$$;

-- 일 마감(기존 `RetailDailyReport` 모양). 환불된 계산서는 금액에서 빼고 건수로만 센다.
-- by_category 에는 그린피가 'Green Fees' 로 함께 잡힌다 — 계산서 한 장에 섞여 팔리기 때문이다.
-- by_station 은 프로 샵·스낵바·티 시트 어디서 연 계산서인지로 나눈다.
create or replace function public.pelham_staff_pos_report_daily(p_date date)
returns jsonb
language plpgsql
stable
security definer
set search_path = ''
as $$
begin
  perform public.pelham_require_staff();
  return (
    with live as (
      select * from public.pelham_bills where business_date = p_date and status = 'paid'
    ), refunded as (
      select * from public.pelham_bills where business_date = p_date and status = 'refunded'
    ), lines as (
      select li.* from public.pelham_bill_lines li join live b on b.id = li.bill_id where li.active
    ), pays as (
      select pp.* from public.pelham_bill_payments pp join live b on b.id = pp.bill_id
    )
    select jsonb_build_object(
      'business_date', to_char(p_date, 'YYYY-MM-DD'),
      'sale_count', (select count(*) from live),
      'gross', (select coalesce(sum(subtotal), 0) from live),
      'discount', (select coalesce(sum(discount), 0) from live),
      'tax', (select coalesce(sum(tax), 0) from live),
      'net', (select coalesce(sum(total), 0) from live),
      'tips', (select coalesce(sum(tip), 0) from live),
      'refunded_count', (select count(*) from refunded),
      'refunded_total', (select coalesce(sum(total), 0) from refunded),
      'by_payment', coalesce((
        select jsonb_agg(jsonb_build_object('method', method, 'count', n, 'total', t)
                         order by array_position(array['cash', 'card', 'debit', 'member_account', 'gift_card'], method))
          from (select method, count(*) as n, sum(amount) as t from pays group by method) s
      ), '[]'::jsonb),
      'by_category', coalesce((
        select jsonb_agg(jsonb_build_object('category', category, 'quantity', q, 'total', t)
                         order by array_position(array['Green Fees', 'Apparel', 'Equipment', 'Balls',
                                                       'Accessories', 'Food & Beverage', 'Rentals'], category))
          from (select category, sum(quantity) as q, sum(line_total) as t from lines group by category) s
      ), '[]'::jsonb),
      'by_station', coalesce((
        select jsonb_agg(jsonb_build_object('station', station, 'count', n, 'total', t) order by station)
          from (select station, count(*) as n, sum(total) as t from live group by station) s
      ), '[]'::jsonb),
      'top_products', coalesce((
        select jsonb_agg(jsonb_build_object('product_id', product_id, 'name', name, 'quantity', q, 'total', t)
                         order by q desc, t desc, product_id)
          from (select product_id, min(name) as name, sum(quantity) as q, sum(line_total) as t
                  from lines where kind = 'product' group by product_id
                 order by q desc, t desc, product_id limit 5) s
      ), '[]'::jsonb)
    )
  );
end;
$$;

-- ===== 권한 ============================================================

revoke all on function public.pelham_pos_tax(integer) from public, anon, authenticated;
revoke all on function public.pelham_pos_today() from public, anon, authenticated;
revoke all on function public.pelham_pos_product_json(public.pelham_retail_products) from public, anon, authenticated;
revoke all on function public.pelham_pos_tee_price(jsonb, jsonb) from public, anon, authenticated;
revoke all on function public.pelham_pos_find_player(jsonb, text) from public, anon, authenticated;
revoke all on function public.pelham_pos_move(integer, integer, text, bigint, text) from public, anon, authenticated;
revoke all on function public.pelham_pos_recalc(bigint) from public, anon, authenticated;
revoke all on function public.pelham_pos_tee_line_name(jsonb, jsonb) from public, anon, authenticated;
revoke all on function public.pelham_pos_bill_json(bigint) from public, anon, authenticated;
revoke all on function public.pelham_pos_lock_open(bigint) from public, anon, authenticated;
revoke all on function public.pelham_pos_check_product(jsonb) from public, anon, authenticated;
revoke all on function public.pelham_pos_guard_tee() from public, anon, authenticated;

revoke all on function public.pelham_staff_pos_products(boolean) from public, anon, authenticated;
revoke all on function public.pelham_staff_pos_product_create(jsonb) from public, anon, authenticated;
revoke all on function public.pelham_staff_pos_product_update(integer, jsonb) from public, anon, authenticated;
revoke all on function public.pelham_staff_pos_product_deactivate(integer) from public, anon, authenticated;
revoke all on function public.pelham_staff_pos_low_stock() from public, anon, authenticated;
revoke all on function public.pelham_staff_bill_open(jsonb) from public, anon, authenticated;
revoke all on function public.pelham_staff_bills_open() from public, anon, authenticated;
revoke all on function public.pelham_staff_bill(bigint) from public, anon, authenticated;
revoke all on function public.pelham_staff_bill_add_product(bigint, integer, integer) from public, anon, authenticated;
revoke all on function public.pelham_staff_bill_line_update(bigint, bigint, jsonb) from public, anon, authenticated;
revoke all on function public.pelham_staff_bill_update(bigint, jsonb) from public, anon, authenticated;
revoke all on function public.pelham_staff_bill_add_tee(bigint, text, text[]) from public, anon, authenticated;
revoke all on function public.pelham_staff_bill_void(bigint) from public, anon, authenticated;
revoke all on function public.pelham_staff_bill_pay(bigint, jsonb) from public, anon, authenticated;
revoke all on function public.pelham_staff_bill_refund(bigint, text) from public, anon, authenticated;
revoke all on function public.pelham_staff_bills(date) from public, anon, authenticated;
revoke all on function public.pelham_staff_bill_by_receipt(text) from public, anon, authenticated;
revoke all on function public.pelham_staff_pos_report_daily(date) from public, anon, authenticated;

grant execute on function public.pelham_staff_pos_products(boolean) to authenticated;
grant execute on function public.pelham_staff_pos_product_create(jsonb) to authenticated;
grant execute on function public.pelham_staff_pos_product_update(integer, jsonb) to authenticated;
grant execute on function public.pelham_staff_pos_product_deactivate(integer) to authenticated;
grant execute on function public.pelham_staff_pos_low_stock() to authenticated;
grant execute on function public.pelham_staff_bill_open(jsonb) to authenticated;
grant execute on function public.pelham_staff_bills_open() to authenticated;
grant execute on function public.pelham_staff_bill(bigint) to authenticated;
grant execute on function public.pelham_staff_bill_add_product(bigint, integer, integer) to authenticated;
grant execute on function public.pelham_staff_bill_line_update(bigint, bigint, jsonb) to authenticated;
grant execute on function public.pelham_staff_bill_update(bigint, jsonb) to authenticated;
grant execute on function public.pelham_staff_bill_add_tee(bigint, text, text[]) to authenticated;
grant execute on function public.pelham_staff_bill_void(bigint) to authenticated;
grant execute on function public.pelham_staff_bill_pay(bigint, jsonb) to authenticated;
grant execute on function public.pelham_staff_bill_refund(bigint, text) to authenticated;
grant execute on function public.pelham_staff_bills(date) to authenticated;
grant execute on function public.pelham_staff_bill_by_receipt(text) to authenticated;
grant execute on function public.pelham_staff_pos_report_daily(date) to authenticated;
