-- 담당자별 마감 + 팁을 근무시간으로 나누기.
--
-- 왜: 하루 마감(0005 `pelham_staff_pos_report_daily`)은 클럽 전체 숫자 하나뿐이다. 계산대를
-- 여러 사람이 돌리면 "누가 받은 현금이 얼마인가" 를 사람별로 맞춰 볼 수 없다. 또 팁은 결제 줄마다
-- 적히지만(`pelham_bill_payments.tip`) 나누는 규칙이 없었다. 클럽은 2026-10-01 에 정했다.
--   1) 마감은 **담당자별**로 한다. 각자 자기 매출·현금을 세어 닫는다.
--   2) 팁은 그날 받은 팁 전부를 한 통에 모아 **근무시간 비율**로 나눈다.
--
-- 담당자 = 계산서의 `cashier` 칸(직원이 적는 이름). 직원 로그인은 공용 계정 하나라
-- `auth.uid()` 로는 사람을 가를 수 없다. 이름은 앞뒤 공백을 떼고 소문자로 묶는다
-- ("Alex " 와 "alex" 는 한 사람). 이름 없는 계산서는 "Unassigned" 로 따로 보인다 —
-- 그 현금은 아무의 서랍에도 잡히지 않지만 팁은 통에 들어간다.
--
-- 마감 한 줄(`pelham_staff_closeouts`) = (영업일, 담당자) 하나. 다시 마감하면 덮어쓴다.
--   - 근무시간은 **분 정수**(금액이 센트 정수인 것과 같은 이유). 화면이 "7.5" 나 "7:30" 을 분으로 바꾼다.
--   - 마감 순간의 기대 현금·매출 건수·매출·팁을 같이 적어 둔다. 마감 뒤에 그 이름으로 결제가 더
--     들어오거나 환불되면 리포트가 "마감 뒤에 바뀜" 을 알린다(다시 마감하면 된다).
--   - 매출이 없는 사람(주방·카트 담당)도 시간만 적고 마감할 수 있다 — 팁은 근무시간으로 나누니까.
--
-- 기대 현금 = 그 사람 이름의 결제된 계산서에서 현금 결제 줄의 (amount + tip).
--   amount 는 계산서에 들어간 몫뿐이다(거스름돈은 화면이 계산하고 서버로 오지 않는다).
--   환불된 계산서는 0005 일 마감과 같이 뺀다. 시작 잔돈(float)은 세지 않는다 — 센 현금에서 빼고 적는다.
--
-- 팁 나누기: 통 = 그날 결제된 계산서의 팁 합(이름 없는 계산서 포함). 마감하면서 근무시간을 적은
--   사람만 나눈다. 몫 = 통 × 내 분 ÷ 전체 분 을 센트로 내리고, 남는 센트는 나머지가 큰 사람부터
--   1센트씩(같으면 이름순). 그래서 몫의 합이 통과 **정확히** 같다. 매출이 있는데 아직 마감하지 않은
--   사람이 있으면 리포트가 `provisional = true` 로 알린다.
--
-- 규칙은 0005 와 같다: `pelham_` 접두사, 테이블은 RLS 켜고 정책 없음, 직원 함수만 authenticated 에게,
-- 오류는 PTxxx. 전제: 0005. 실행: SQL editor 에 이 파일 전체를 붙여 한 번. 다시 실행해도 안전하다.

do $$
begin
  if to_regclass('public.pelham_bills') is null or to_regclass('public.pelham_bill_payments') is null then
    raise exception '0010 needs 0005 first (pelham_bills / pelham_bill_payments is missing).';
  end if;
  if to_regprocedure('public.pelham_require_staff()') is null or to_regprocedure('public.pelham_pos_today()') is null then
    raise exception '0010 needs 0004 and 0005 first (pelham_require_staff / pelham_pos_today is missing).';
  end if;
end;
$$;

-- ===== 테이블 ==========================================================

create table if not exists public.pelham_staff_closeouts (
  id              bigint generated by default as identity primary key,
  business_date   date not null,
  -- lower(btrim(이름)). 계산서의 cashier 를 같은 식으로 묶는다.
  staff_key       text not null check (length(staff_key) between 1 and 60),
  -- 화면에 보이는 이름(마지막으로 적은 모양).
  staff_name      text not null check (length(btrim(staff_name)) between 1 and 60),
  minutes_worked  integer not null check (minutes_worked between 0 and 1440),
  -- 센 현금(시작 잔돈 뺀 값). 현금을 안 만진 사람은 null.
  counted_cash    integer check (counted_cash is null or counted_cash >= 0),
  -- 마감 순간의 값. 뒤에 바뀌면 리포트가 알린다.
  expected_cash   integer not null default 0,
  sale_count      integer not null default 0,
  net             integer not null default 0,
  tips_taken      integer not null default 0,
  note            text,
  closed_by       uuid,
  closed_at       timestamptz not null default now(),
  unique (business_date, staff_key)
);

alter table public.pelham_staff_closeouts enable row level security;
revoke all on public.pelham_staff_closeouts from anon, authenticated;

-- ===== 헬퍼 (직원 확인 없음 — 실행 권한을 아무에게도 주지 않는다) ========

create or replace function public.pelham_staff_key(p_name text)
returns text
language sql
immutable
set search_path = ''
as $$
  select coalesce(lower(regexp_replace(btrim(coalesce(p_name, '')), '\s+', ' ', 'g')), '')
$$;

-- 한 영업일, 담당자별 숫자(마감 기록 없이). staff_key '' = 이름 없는 계산서.
create or replace function public.pelham_closeout_figures(p_date date)
returns table (staff_key text, staff_name text, sale_count integer, net integer, tips integer,
               expected_cash integer, by_payment jsonb)
language sql
stable
set search_path = ''
as $$
  with live as (
    select b.id, b.total, b.tip, b.cashier, public.pelham_staff_key(b.cashier) as k
      from public.pelham_bills b
     where b.business_date = p_date and b.status = 'paid'
  ), pays as (
    select l.k, pp.method, count(*)::integer as n, sum(pp.amount)::integer as amount, sum(pp.tip)::integer as tip
      from public.pelham_bill_payments pp join live l on l.id = pp.bill_id
     group by l.k, pp.method
  )
  select s.k,
         s.name,
         s.n,
         s.net,
         s.tips,
         coalesce((select p.amount + p.tip from pays p where p.k = s.k and p.method = 'cash'), 0),
         coalesce((
           select jsonb_agg(jsonb_build_object('method', p.method, 'count', p.n, 'total', p.amount, 'tip', p.tip)
                            order by array_position(array['cash', 'card', 'debit', 'member_account', 'gift_card'], p.method))
             from pays p where p.k = s.k
         ), '[]'::jsonb)
    from (
      select k, min(btrim(cashier)) as name, count(*)::integer as n,
             coalesce(sum(total), 0)::integer as net, coalesce(sum(tip), 0)::integer as tips
        from live group by k
    ) s
$$;

-- ===== 직원 함수 ======================================================

-- 담당자별 마감 리포트 + 팁 나누기.
-- {business_date, tip_pool, total_minutes, provisional, staff: [...], unassigned: {...}|null}
create or replace function public.pelham_staff_closeout_report(p_date date)
returns jsonb
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
  v_pool integer;
  v_total integer;
  v_today boolean := p_date = public.pelham_pos_today();
begin
  perform public.pelham_require_staff();
  if p_date is null then
    perform public.pelham_fail('422', '''date'' must be an ISO date (YYYY-MM-DD)');
  end if;

  select coalesce(sum(tip), 0)::integer into v_pool
    from public.pelham_bills where business_date = p_date and status = 'paid';
  select coalesce(sum(minutes_worked), 0)::integer into v_total
    from public.pelham_staff_closeouts where business_date = p_date and minutes_worked > 0;

  return (
    with fig as (
      select * from public.pelham_closeout_figures(p_date)
    ), co as (
      select * from public.pelham_staff_closeouts where business_date = p_date
    ), split as (
      -- 내림 몫 + 남는 센트를 나머지가 큰 순서로. bigint 로 곱한다(팁 $2,000 × 1440분도 넘치지 않게).
      select c.staff_key,
             (v_pool::bigint * c.minutes_worked / v_total)::integer as base,
             row_number() over (order by (v_pool::bigint * c.minutes_worked) % v_total desc, c.staff_key) as rnk
        from co c
       where v_total > 0 and c.minutes_worked > 0
    ), shares as (
      select s.staff_key,
             s.base + case when s.rnk <= v_pool - (select sum(base) from split) then 1 else 0 end as share
        from split s
    ), opens as (
      -- 아직 결제 안 된 계산서. 열린 계산서에는 영업일이 없으니 오늘을 볼 때만 센다.
      select public.pelham_staff_key(b.cashier) as k, count(*)::integer as n
        from public.pelham_bills b
       where v_today and b.status = 'open' and exists (select 1 from public.pelham_bill_lines li where li.bill_id = b.id and li.active)
       group by 1
    ), people as (
      select f.staff_key as k from fig f where f.staff_key <> ''
      union
      select c.staff_key from co c
    )
    select jsonb_build_object(
      'business_date', to_char(p_date, 'YYYY-MM-DD'),
      'tip_pool', v_pool,
      'total_minutes', v_total,
      -- 매출이 있는데 아직 안 닫은 사람이 있으면 몫이 바뀔 수 있다.
      'provisional', exists (select 1 from fig f where f.staff_key <> ''
                                and not exists (select 1 from co c where c.staff_key = f.staff_key)),
      'staff', coalesce((
        select jsonb_agg(jsonb_build_object(
                 'staff_key', p.k,
                 'name', coalesce(c.staff_name, f.staff_name),
                 'sale_count', coalesce(f.sale_count, 0),
                 'net', coalesce(f.net, 0),
                 'tips_taken', coalesce(f.tips, 0),
                 'expected_cash', coalesce(f.expected_cash, 0),
                 'by_payment', coalesce(f.by_payment, '[]'::jsonb),
                 'open_bills', coalesce(o.n, 0),
                 'tip_share', sh.share,
                 'closeout', case when c.id is null then null else jsonb_build_object(
                   'minutes_worked', c.minutes_worked,
                   'counted_cash', c.counted_cash,
                   'expected_cash', c.expected_cash,
                   'sale_count', c.sale_count,
                   'net', c.net,
                   'tips_taken', c.tips_taken,
                   'note', c.note,
                   'closed_at', public.pelham_iso(c.closed_at),
                   -- 닫은 뒤 그 이름으로 결제·환불이 있었다.
                   'stale', (c.sale_count, c.net, c.expected_cash, c.tips_taken)
                            is distinct from (coalesce(f.sale_count, 0), coalesce(f.net, 0),
                                              coalesce(f.expected_cash, 0), coalesce(f.tips, 0))
                 ) end
               ) order by coalesce(c.staff_name, f.staff_name))
          from people p
          left join fig f on f.staff_key = p.k
          left join co c on c.staff_key = p.k
          left join shares sh on sh.staff_key = p.k
          left join opens o on o.k = p.k
      ), '[]'::jsonb),
      'unassigned', (
        select jsonb_build_object('sale_count', f.sale_count, 'net', f.net, 'tips_taken', f.tips,
                                  'expected_cash', f.expected_cash, 'by_payment', f.by_payment,
                                  'open_bills', coalesce((select n from opens where k = ''), 0))
          from fig f where f.staff_key = ''
      )
    )
  );
end;
$$;

-- 마감(또는 다시 마감). p: {name, minutes_worked, counted_cash?, note?}. 리포트 전체를 돌려준다.
create or replace function public.pelham_staff_closeout_save(p_date date, p jsonb)
returns jsonb
language plpgsql
volatile
security definer
set search_path = ''
as $$
declare
  v_name text;
  v_key text;
  v_minutes integer;
  v_cash integer;
  v_expected integer := 0;
  v_count integer := 0;
  v_net integer := 0;
  v_tips integer := 0;
begin
  perform public.pelham_require_staff();
  p := coalesce(p, '{}'::jsonb);
  if p_date is null then
    perform public.pelham_fail('422', '''date'' must be an ISO date (YYYY-MM-DD)');
  end if;
  if p_date > public.pelham_pos_today() then
    perform public.pelham_fail('422', 'You cannot close out a day that has not started.');
  end if;

  v_name := regexp_replace(btrim(coalesce(p->>'name', '')), '\s+', ' ', 'g');
  v_key := public.pelham_staff_key(v_name);
  if length(v_name) = 0 or length(v_name) > 60 then
    perform public.pelham_fail('422', 'Enter the staff member''s name (up to 60 characters).');
  end if;

  begin
    v_minutes := (p->>'minutes_worked')::integer;
    v_cash := nullif(p->>'counted_cash', '')::integer;
  exception when others then
    perform public.pelham_fail('422', 'Hours and counted cash must be whole numbers (minutes, cents).');
  end;
  if v_minutes is null or v_minutes < 0 or v_minutes > 1440 then
    perform public.pelham_fail('422', 'Hours worked must be between 0 and 24.');
  end if;
  if v_cash is not null and v_cash < 0 then
    perform public.pelham_fail('422', 'Counted cash cannot be negative.');
  end if;

  -- 매출이 없는 사람(시간만 적는 사람)은 줄이 없다. 그러면 0 그대로.
  select x.expected_cash, x.sale_count, x.net, x.tips into v_expected, v_count, v_net, v_tips
    from public.pelham_closeout_figures(p_date) x where x.staff_key = v_key;

  insert into public.pelham_staff_closeouts as c
    (business_date, staff_key, staff_name, minutes_worked, counted_cash, expected_cash, sale_count, net,
     tips_taken, note, closed_by, closed_at)
  values (p_date, v_key, v_name, v_minutes, v_cash, coalesce(v_expected, 0), coalesce(v_count, 0),
          coalesce(v_net, 0), coalesce(v_tips, 0), nullif(btrim(coalesce(p->>'note', '')), ''), auth.uid(), now())
  on conflict (business_date, staff_key) do update
    set staff_name = excluded.staff_name, minutes_worked = excluded.minutes_worked,
        counted_cash = excluded.counted_cash, expected_cash = excluded.expected_cash,
        sale_count = excluded.sale_count, net = excluded.net, tips_taken = excluded.tips_taken,
        note = excluded.note, closed_by = excluded.closed_by, closed_at = excluded.closed_at;

  return public.pelham_staff_closeout_report(p_date);
end;
$$;

-- 마감 취소(이름을 잘못 적었을 때 등). 매출은 건드리지 않는다.
create or replace function public.pelham_staff_closeout_reopen(p_date date, p_staff_key text)
returns jsonb
language plpgsql
volatile
security definer
set search_path = ''
as $$
begin
  perform public.pelham_require_staff();
  delete from public.pelham_staff_closeouts
   where business_date = p_date and staff_key = public.pelham_staff_key(p_staff_key);
  if not found then
    perform public.pelham_fail('404', 'That close-out does not exist.');
  end if;
  return public.pelham_staff_closeout_report(p_date);
end;
$$;

-- ===== 권한 ============================================================

revoke all on function public.pelham_staff_key(text) from public, anon, authenticated;
revoke all on function public.pelham_closeout_figures(date) from public, anon, authenticated;
revoke all on function public.pelham_staff_closeout_report(date) from public, anon, authenticated;
revoke all on function public.pelham_staff_closeout_save(date, jsonb) from public, anon, authenticated;
revoke all on function public.pelham_staff_closeout_reopen(date, text) from public, anon, authenticated;

grant execute on function public.pelham_staff_closeout_report(date) to authenticated;
grant execute on function public.pelham_staff_closeout_save(date, jsonb) to authenticated;
grant execute on function public.pelham_staff_closeout_reopen(date, text) to authenticated;
