-- 레인체크(rain check): 비로 라운드를 다 못 친 손님에게 **사람마다** 한 장씩 주는 크레딧 전표.
--
-- 흐름
--   1) 티 시트에서 결제한(paid) 플레이어 카드의 Rain check 를 누른다. 금액과 만료일을 확인하고
--      발행하면 서버가 코드(`RC-` + 무작위 10자)를 매기고, 화면이 그 코드를 Code 128 바코드로 담은
--      전표를 사람마다 한 장씩 찍는다(손님용 + 보관용).
--   2) 다음에 오면 계산서 결제에서 수단 "Rain check" 를 고르고 전표 바코드를 쏜다. 서버가 코드를
--      잠그고 상태(발행됨)·만료일·금액을 확인한 뒤, 결제와 **같은 트랜잭션**에서 사용됨으로 바꾼다.
--
-- 규칙
-- - 한 사람(예약의 플레이어 하나)에게 살아 있는 레인체크는 하나뿐이다. 다시 찍을 때는 같은 코드로
--   재인쇄한다(REPRINT 표시). 잘못 발행했으면 사유를 적고 무효(void)로 한 뒤 다시 발행한다.
-- - 금액(센트, 세금 포함)의 기본값은 **그 사람이 실제로 낸 돈**이다. 계산서로 받은 그린피는 그 줄에서
--   읽는다(줄 할인 뒤 + 계산서 할인 몫을 빼고 + 세금 몫). GolfNow 선결제·컴프처럼 $0 으로 닫힌
--   사람에게 정가 크레딧이 나가면 안 되기 때문이다. 계산서 이전 방식(티 시트 토글)으로 낸 사람만
--   예약의 그린피 + 카트 + HST 로 계산한다. 직원은 금액을 낮출 수 있지만 낸 돈보다 높일 수는 없다.
--   몇 홀을 쳤을 때 얼마를 돌려주는지는 클럽 정책이라 여기서 정하지 않는다.
-- - 만료일의 기본값은 발행일 + 1년(`pelham_rc_default_expiry`). 발행 창에서 바꿀 수 있다.
--   만료 판정은 매장 현지 날짜(토론토)로 한다 — 만료일 당일까지 쓸 수 있다.
-- - 크레딧은 한 번에 쓴다. 계산서가 크레딧보다 작으면 남는 몫은 사라진다(화면이 미리 경고한다).
-- - 레인체크를 발행한 계산서를 환불하면: 아직 안 쓴 레인체크는 무효가 되고, 이미 쓴 것이 있으면
--   환불을 거절한다(돈을 두 번 돌려주게 된다). 레인체크로 결제한 계산서를 환불하면 그 레인체크는
--   다시 쓸 수 있는 상태로 돌아간다.
-- - 살아 있는 레인체크가 있는 플레이어는 티 시트에서 "Mark unpaid"·삭제할 수 없다.
--
-- 회계: 레인체크로 받은 돈은 결제 수단 `rain_check` 로 따로 잡힌다(현금 시재에 들어가지 않는다).
--
-- 공유 프로젝트 규칙(0005 와 같다): 전부 `pelham_` 접두사, 테이블은 RLS 를 켜고 정책 없음,
-- 직원 함수는 첫 줄이 `pelham_require_staff()`. 오류는 PT404/PT409/PT422.
--
-- 전제: 0005(계산서). 0006–0010 과는 독립이다.
-- 실행: SQL editor 에 이 파일 전체를 붙여 한 번. 다시 실행해도 안전하다.

-- ===== 먼저 확인 ======================================================
do $$
declare
  v_missing text[] := '{}';
  v_name text;
begin
  foreach v_name in array array['pelham_fail', 'pelham_iso', 'pelham_require_staff', 'pelham_tee_audit',
                                 'pelham_tee_save', 'pelham_tee_lock', 'pelham_pos_today', 'pelham_pos_tax',
                                 'pelham_pos_find_player', 'pelham_pos_tee_price', 'pelham_pos_lock_open',
                                 'pelham_pos_recalc', 'pelham_pos_move', 'pelham_staff_bill_pay'] loop
    if not exists (select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace
                    where n.nspname = 'public' and p.proname = v_name) then
      v_missing := v_missing || (v_name || '()');
    end if;
  end loop;
  if to_regclass('public.pelham_bill_payments') is null then
    v_missing := v_missing || 'pelham_bill_payments'::text;
  end if;
  if cardinality(v_missing) > 0 then
    raise exception '0011 needs 0005 first. Missing: %', array_to_string(v_missing, ', ');
  end if;
end;
$$;

-- ===== 테이블 ==========================================================

create table if not exists public.pelham_rain_checks (
  id                bigint generated by default as identity primary key,
  -- 전표의 바코드 값. 무작위다 — 순번이면 옆 번호를 쳐서 남의 크레딧을 쓸 수 있다.
  code              text not null unique check (code ~ '^RC-[0-9A-F]{10}$'),
  status            text not null default 'issued' check (status in ('issued', 'redeemed', 'void')),
  -- 누구의 어느 라운드인가. 이름·날짜는 발행 시점 값을 복사한다(예약이 바뀌어도 전표는 그대로).
  booking_id        text not null,
  player_id         text not null,
  player_name       text not null,
  tee_date          date,
  tee_time          text,
  holes             integer,
  -- 직원이 적은 친 홀 수. 전표에 찍히는 참고값이고 금액을 정하지 않는다.
  holes_played      integer check (holes_played is null or holes_played between 0 and 18),
  -- 크레딧(센트, 세금 포함)과 그 사람이 낸 돈(발행 당시 계산값, 상한).
  amount            integer not null check (amount > 0),
  paid_value        integer not null check (paid_value >= 0),
  -- 그린피를 받은 계산서. 티 시트 토글로 받았으면 null.
  source_bill_id    bigint references public.pelham_bills (id),
  issued_on         date not null,
  expires_on        date not null,
  cashier           text,
  note              text,
  issued_by         uuid,
  issued_at         timestamptz not null default now(),
  redeemed_bill_id  bigint references public.pelham_bills (id),
  redeemed_at       timestamptz,
  void_reason       text,
  voided_at         timestamptz,
  check (expires_on >= issued_on),
  check ((status = 'redeemed') = (redeemed_bill_id is not null)),
  check ((status = 'void') = (voided_at is not null))
);
-- 한 사람에게 살아 있는(발행·사용) 레인체크는 하나.
create unique index if not exists pelham_rain_checks_player_once
  on public.pelham_rain_checks (booking_id, player_id) where status in ('issued', 'redeemed');
create index if not exists pelham_rain_checks_booking_idx on public.pelham_rain_checks (booking_id);
create index if not exists pelham_rain_checks_source_idx on public.pelham_rain_checks (source_bill_id);
create index if not exists pelham_rain_checks_redeemed_idx on public.pelham_rain_checks (redeemed_bill_id);

alter table public.pelham_rain_checks enable row level security;
revoke all on public.pelham_rain_checks from anon, authenticated;

-- 결제 줄: 수단에 rain_check 를 더하고, 어느 레인체크인지 적는다.
alter table public.pelham_bill_payments
  add column if not exists rain_check_id bigint references public.pelham_rain_checks (id);

-- 0005 의 이름 없는 method check 를 정의로 찾아 바꾼다(0008 이 kind 를 바꾼 방식과 같다).
do $$
declare
  c record;
begin
  for c in
    select conname from pg_constraint
     where conrelid = 'public.pelham_bill_payments'::regclass and contype = 'c'
       and pg_get_constraintdef(oid) like '%method = ANY%'
  loop
    execute format('alter table public.pelham_bill_payments drop constraint %I', c.conname);
  end loop;
  alter table public.pelham_bill_payments add constraint pelham_bill_payments_method_check
    check (method in ('cash', 'card', 'debit', 'member_account', 'gift_card', 'rain_check'));

  if not exists (select 1 from pg_constraint where conname = 'pelham_bill_payments_rain_check_check') then
    alter table public.pelham_bill_payments add constraint pelham_bill_payments_rain_check_check
      check ((method = 'rain_check') = (rain_check_id is not null));
  end if;
end;
$$;

-- ===== 헬퍼 (실행 권한을 아무에게도 주지 않는다) ========================

-- 기본 만료일: 발행일 + 1년. 클럽 정책이 정해지면 여기 한 곳만 바꾼다.
create or replace function public.pelham_rc_default_expiry(p_issued date)
returns date
language sql
immutable
set search_path = ''
as $$
  select (p_issued + interval '1 year')::date
$$;

create or replace function public.pelham_rc_json(r public.pelham_rain_checks)
returns jsonb
language sql
stable
set search_path = ''
as $$
  select jsonb_build_object(
    'id', r.id,
    'code', r.code,
    'status', r.status,
    -- 화면이 "만료됨"을 따로 보여 준다. 상태를 바꾸지는 않는다(만료는 날짜로만 판정).
    'expired', r.status = 'issued' and r.expires_on < public.pelham_pos_today(),
    'booking_id', r.booking_id,
    'player_id', r.player_id,
    'player_name', r.player_name,
    'tee_date', to_char(r.tee_date, 'YYYY-MM-DD'),
    'tee_time', r.tee_time,
    'holes', r.holes,
    'holes_played', r.holes_played,
    'amount', r.amount,
    'paid_value', r.paid_value,
    'source_receipt', (select b.receipt_no from public.pelham_bills b where b.id = r.source_bill_id),
    'issued_on', to_char(r.issued_on, 'YYYY-MM-DD'),
    'expires_on', to_char(r.expires_on, 'YYYY-MM-DD'),
    'cashier', r.cashier,
    'note', r.note,
    'issued_at', public.pelham_iso(r.issued_at),
    'redeemed_receipt', (select b.receipt_no from public.pelham_bills b where b.id = r.redeemed_bill_id),
    'redeemed_at', public.pelham_iso(r.redeemed_at),
    'void_reason', r.void_reason,
    'voided_at', public.pelham_iso(r.voided_at)
  )
$$;

-- 한 플레이어가 낸 돈(센트, 세금 포함)과 그 계산서. 레인체크 금액의 기본값이자 상한.
-- 계산서로 받았으면 그 줄: 줄 합계(줄 할인 뒤) − 계산서 할인의 이 줄 몫 + 세금의 이 줄 몫.
-- 몫은 줄 합계 비율로 나눈다. 계산서 이전 방식이면 예약의 그린피 + 카트 + HST.
create or replace function public.pelham_rc_paid_value(p_booking text, p_doc jsonb, p_player jsonb,
                                                       out paid_value integer, out bill_id bigint)
language plpgsql
stable
set search_path = ''
as $$
declare
  l record;
  v_net integer;
  v_taxable integer;
begin
  select li.line_total, b.id, b.subtotal, b.discount, b.tax into l
    from public.pelham_bill_lines li join public.pelham_bills b on b.id = li.bill_id
   where li.booking_id = p_booking and li.player_id = p_player->>'id'
     and li.kind = 'tee_player' and li.active and b.status = 'paid'
   order by b.paid_at desc
   limit 1;
  if l.id is not null then
    bill_id := l.id;
    v_net := l.line_total;
    if l.subtotal > 0 and l.discount > 0 then
      v_net := v_net - round(l.discount::numeric * l.line_total / l.subtotal)::integer;
    end if;
    v_net := greatest(v_net, 0);
    v_taxable := l.subtotal - l.discount;
    paid_value := v_net + case when v_taxable > 0
                               then round(l.tax::numeric * v_net / v_taxable)::integer else 0 end;
  else
    bill_id := null;
    v_net := public.pelham_pos_tee_price(p_doc, p_player);
    paid_value := v_net + public.pelham_pos_tax(v_net);
  end if;
end;
$$;

-- ===== 직원 함수 ======================================================

-- 발행 전 확인: 이 사람이 낸 돈(기본 금액), 기본 만료일, 이미 있는 레인체크.
create or replace function public.pelham_staff_rain_check_quote(p_booking text, p_player text)
returns jsonb
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
  v_doc jsonb;
  v_player jsonb;
  v_paid integer;
  v_bill bigint;
  v_today date := public.pelham_pos_today();
  r public.pelham_rain_checks;
begin
  perform public.pelham_require_staff();
  select t.doc into v_doc from public.pelham_tee_bookings t where t.id = p_booking;
  if v_doc is null then
    perform public.pelham_fail('404', 'Booking not found');
  end if;
  v_player := public.pelham_pos_find_player(v_doc, p_player);
  if v_player is null then
    perform public.pelham_fail('404', 'Player not found on this reservation');
  end if;
  select * into r from public.pelham_rain_checks
   where booking_id = p_booking and player_id = p_player and status in ('issued', 'redeemed');
  select q.paid_value, q.bill_id into v_paid, v_bill from public.pelham_rc_paid_value(p_booking, v_doc, v_player) q;
  return jsonb_build_object(
    'player_name', coalesce(nullif(btrim(v_player->>'name'), ''), 'Guest'),
    'paid', coalesce((v_player->>'paid')::boolean, false),
    'paid_value', v_paid,
    'source_receipt', (select b.receipt_no from public.pelham_bills b where b.id = v_bill),
    'issued_on', to_char(v_today, 'YYYY-MM-DD'),
    'default_expires_on', to_char(public.pelham_rc_default_expiry(v_today), 'YYYY-MM-DD'),
    'existing', case when r.id is null then null else public.pelham_rc_json(r) end
  );
end;
$$;

-- 발행. p: {booking_id, player_id, amount?, expires_on?, holes_played?, cashier?, note?}
create or replace function public.pelham_staff_rain_check_issue(p jsonb)
returns jsonb
language plpgsql
volatile
security definer
set search_path = ''
as $$
declare
  v_doc jsonb;
  v_player jsonb;
  v_booking text := p->>'booking_id';
  v_player_id text := p->>'player_id';
  v_paid integer;
  v_bill bigint;
  v_amount integer;
  v_today date := public.pelham_pos_today();
  v_expires date;
  v_holes_played integer;
  v_code text;
  v_name text;
  r public.pelham_rain_checks;
begin
  perform public.pelham_require_staff();
  p := coalesce(p, '{}'::jsonb);
  if v_booking is null or v_player_id is null then
    perform public.pelham_fail('422', 'booking_id and player_id are required.');
  end if;

  select t.doc into v_doc from public.pelham_tee_bookings t where t.id = v_booking;
  if v_doc is null then
    perform public.pelham_fail('404', 'Booking not found');
  end if;
  -- 티 시트 쓰기와 같은 잠금 순서(슬롯 → 예약 행). 결제·환불과 엇갈리지 않게.
  perform public.pelham_tee_lock((v_doc->>'date')::date, v_doc->>'time');
  select t.doc into v_doc from public.pelham_tee_bookings t where t.id = v_booking for update;

  v_player := public.pelham_pos_find_player(v_doc, v_player_id);
  if v_player is null then
    perform public.pelham_fail('404', 'Player not found on this reservation');
  end if;
  v_name := coalesce(nullif(btrim(v_player->>'name'), ''), 'Guest');
  if coalesce((v_player->>'cancelled')::boolean, false) then
    perform public.pelham_fail('409', format('%s is cancelled.', v_name));
  end if;
  if not coalesce((v_player->>'paid')::boolean, false) then
    perform public.pelham_fail('409', format('%s has not paid. A rain check is credit for a paid round.', v_name));
  end if;
  select code into v_code from public.pelham_rain_checks
   where booking_id = v_booking and player_id = v_player_id and status in ('issued', 'redeemed');
  if v_code is not null then
    perform public.pelham_fail('409', format('%s already has rain check %s. Reprint it, or void it first.', v_name, v_code));
  end if;

  select q.paid_value, q.bill_id into v_paid, v_bill from public.pelham_rc_paid_value(v_booking, v_doc, v_player) q;
  begin
    v_amount := coalesce((p->>'amount')::integer, v_paid);
    v_expires := coalesce(nullif(p->>'expires_on', '')::date, public.pelham_rc_default_expiry(v_today));
    v_holes_played := nullif(p->>'holes_played', '')::integer;
  exception when others then
    perform public.pelham_fail('422', 'amount (cents), expires_on (YYYY-MM-DD) or holes_played is not valid.');
  end;
  if v_amount <= 0 then
    perform public.pelham_fail('422', format('%s paid nothing for this round, so there is no credit to give.', v_name));
  end if;
  if v_amount > v_paid then
    perform public.pelham_fail('422', format('A rain check cannot be more than %s paid (%s cents).', v_name, v_paid));
  end if;
  if v_expires < v_today then
    perform public.pelham_fail('422', 'The expiry date is in the past.');
  end if;
  if v_expires > (v_today + interval '3 years')::date then
    perform public.pelham_fail('422', 'The expiry date is more than three years away.');
  end if;
  if v_holes_played is not null and v_holes_played not between 0 and 18 then
    perform public.pelham_fail('422', 'Holes played must be between 0 and 18.');
  end if;

  -- 코드: 무작위 10자(16진). 겹치면 다시 뽑는다.
  loop
    v_code := 'RC-' || upper(substr(replace(gen_random_uuid()::text, '-', ''), 1, 10));
    exit when not exists (select 1 from public.pelham_rain_checks where code = v_code);
  end loop;

  insert into public.pelham_rain_checks
    (code, booking_id, player_id, player_name, tee_date, tee_time, holes, holes_played,
     amount, paid_value, source_bill_id, issued_on, expires_on, cashier, note, issued_by)
  values
    (v_code, v_booking, v_player_id, v_name, (v_doc->>'date')::date, v_doc->>'time',
     nullif(v_doc->>'holes', '')::integer, v_holes_played, v_amount, v_paid, v_bill, v_today, v_expires,
     nullif(btrim(coalesce(p->>'cashier', '')), ''), nullif(btrim(coalesce(p->>'note', '')), ''), auth.uid())
  returning * into r;

  v_doc := public.pelham_tee_audit(v_doc,
             format('Rain check %s issued to %s: %s, valid through %s.', v_code, v_name,
                    '$' || to_char(v_amount / 100.0, 'FM999,990.00'), to_char(v_expires, 'YYYY-MM-DD')),
             public.pelham_iso(now()));
  perform public.pelham_tee_save(v_doc);

  return public.pelham_rc_json(r);
end;
$$;

-- 한 예약의 레인체크 전부(무효 포함, 발행 순). 플레이어 카드가 상태를 보여 준다.
create or replace function public.pelham_staff_rain_checks(p_booking text)
returns jsonb
language plpgsql
stable
security definer
set search_path = ''
as $$
begin
  perform public.pelham_require_staff();
  return coalesce((
    select jsonb_agg(public.pelham_rc_json(r) order by r.issued_at, r.id)
      from public.pelham_rain_checks r where r.booking_id = p_booking
  ), '[]'::jsonb);
end;
$$;

-- 코드로 찾기(결제 칸에서 전표를 쐈을 때). 쓸 수 있는지는 화면이 status·expired 로 보여 주고,
-- 실제 판정은 결제 함수가 잠금 안에서 다시 한다.
create or replace function public.pelham_staff_rain_check(p_code text)
returns jsonb
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
  r public.pelham_rain_checks;
begin
  perform public.pelham_require_staff();
  select * into r from public.pelham_rain_checks where code = upper(btrim(coalesce(p_code, '')));
  if r.id is null then
    perform public.pelham_fail('404', format('No rain check %s', coalesce(p_code, '')));
  end if;
  return public.pelham_rc_json(r);
end;
$$;

-- 무효. 아직 안 쓴 것만. 사유는 필수 — 크레딧을 없애는 일이다.
create or replace function public.pelham_staff_rain_check_void(p_code text, p_reason text)
returns jsonb
language plpgsql
volatile
security definer
set search_path = ''
as $$
declare
  r public.pelham_rain_checks;
begin
  perform public.pelham_require_staff();
  if length(btrim(coalesce(p_reason, ''))) = 0 then
    perform public.pelham_fail('422', 'Give a reason for voiding the rain check.');
  end if;
  select * into r from public.pelham_rain_checks where code = upper(btrim(coalesce(p_code, ''))) for update;
  if r.id is null then
    perform public.pelham_fail('404', format('No rain check %s', coalesce(p_code, '')));
  end if;
  if r.status <> 'issued' then
    perform public.pelham_fail('409', format('Rain check %s is already %s.', r.code, r.status));
  end if;
  update public.pelham_rain_checks
     set status = 'void', voided_at = now(), void_reason = btrim(p_reason)
   where id = r.id
  returning * into r;
  return public.pelham_rc_json(r);
end;
$$;

-- ===== 0005 함수 다시 정의 =============================================
-- 아래 두 함수는 0005 본문을 그대로 옮기고 레인체크 부분만 더했다(`-- 0011:` 표시).

create or replace function public.pelham_pos_bill_json(p_bill bigint)
returns jsonb
language sql
stable
set search_path = ''
as $$
  select jsonb_build_object(
    'id', b.id,
    'status', b.status,
    'station', b.station,
    'label', b.label,
    'receipt_no', b.receipt_no,
    'business_date', to_char(b.business_date, 'YYYY-MM-DD'),
    'checkout_id', b.checkout_id,
    'lines', coalesce((
      select jsonb_agg(jsonb_build_object(
               'id', l.id,
               'kind', l.kind,
               'product_id', l.product_id,
               'sku', l.sku,
               'name', l.name,
               'category', l.category,
               'quantity', l.quantity,
               'unit_price', l.unit_price,
               'discount', l.discount,
               'line_total', l.line_total,
               'booking_id', l.booking_id,
               'player_id', l.player_id,
               'tee_date', to_char(l.tee_date, 'YYYY-MM-DD'),
               'tee_time', l.tee_time
             ) order by l.id)
        from public.pelham_bill_lines l
       where l.bill_id = b.id
         and (l.active or b.status in ('refunded', 'void'))
    ), '[]'::jsonb),
    'payments', coalesce((
      select jsonb_agg(jsonb_build_object(
               'method', p.method,
               'amount', p.amount,
               'tip', p.tip,
               'entry', p.entry,
               'auth_code', p.auth_code,
               'card_last4', p.card_last4,
               'terminal', p.terminal,
               -- 0011: 레인체크로 낸 줄은 그 코드.
               'rain_check_code', (select r.code from public.pelham_rain_checks r where r.id = p.rain_check_id)
             ) order by p.id)
        from public.pelham_bill_payments p
       where p.bill_id = b.id
    ), '[]'::jsonb),
    -- 기존 `Sale.payment_method` 자리: 첫 결제 수단. 분할 결제면 payments[] 를 본다.
    'payment_method', (select p.method from public.pelham_bill_payments p
                        where p.bill_id = b.id order by p.id limit 1),
    'subtotal', b.subtotal,
    'discount', b.discount,
    'tax', b.tax,
    'total', b.total,
    'tip', b.tip,
    'cashier', b.cashier,
    'note', b.note,
    'opened_at', public.pelham_iso(b.opened_at),
    'paid_at', public.pelham_iso(b.paid_at),
    'refunded_at', public.pelham_iso(b.refunded_at),
    'refund_reason', b.refund_reason,
    -- `Sale.created_at` 은 영수증 시각이다. 결제된 계산서는 결제 시각을 쓴다.
    'created_at', public.pelham_iso(coalesce(b.paid_at, b.opened_at))
  )
  from public.pelham_bills b
  where b.id = p_bill
$$;

-- 결제. 한 트랜잭션 안에서: 금액 재계산 → 결제 검증 → 재고 차감 → 티 시트 paid → 영수증 번호.
-- p: {checkout_id, payments: [{method, amount, tip?, auth_code?, card_last4?, rain_check_code?}]}
create or replace function public.pelham_staff_bill_pay(p_bill bigint, p jsonb)
returns jsonb
language plpgsql
volatile
security definer
set search_path = ''
as $$
declare
  v_bill public.pelham_bills;
  v_checkout uuid;
  v_payments jsonb := coalesce(p->'payments', '[]'::jsonb);
  pay jsonb;
  v_method text;
  v_amount integer;
  v_sum integer := 0;
  v_tips integer := 0;
  l record;
  v_doc jsonb;
  v_player jsonb;
  v_players jsonb;
  v_now text := public.pelham_iso(now());
  v_date date := public.pelham_pos_today();
  v_no integer;
  v_receipt text;
  v_booking text;
  v_names text[];
  v_stock integer;
  v_active boolean;
  -- 0011: 레인체크 결제.
  v_rc public.pelham_rain_checks;
  v_rc_codes text[] := '{}';
  v_rc_ids bigint[] := '{}';
  v_code text;
begin
  perform public.pelham_require_staff();
  p := coalesce(p, '{}'::jsonb);

  begin
    v_checkout := nullif(p->>'checkout_id', '')::uuid;
  exception when others then
    perform public.pelham_fail('422', 'checkout_id must be a UUID.');
  end;
  if v_checkout is null then
    perform public.pelham_fail('422', 'checkout_id is required (one per Charge press).');
  end if;

  -- 계산서를 먼저 잠그고 나서 멱등 키를 본다. 거꾸로 하면 동시에 온 재시도 두 개 중
  -- 뒤의 것이 "이미 결제됨" 오류를 받는다 — 돈은 받았는데 계산대에 빨간 오류가 뜬다.
  select * into v_bill from public.pelham_bills where id = p_bill for update;
  if v_bill.id is null then
    perform public.pelham_fail('404', 'Bill not found');
  end if;
  -- 같은 결제가 두 번 왔다(응답이 끊겨 화면이 다시 보냄). 첫 결과를 그대로 돌려준다.
  if v_bill.checkout_id = v_checkout then
    return public.pelham_pos_bill_json(v_bill.id);
  end if;
  if exists (select 1 from public.pelham_bills where checkout_id = v_checkout and id <> p_bill) then
    perform public.pelham_fail('409', 'This checkout_id belongs to another bill.');
  end if;

  v_bill := public.pelham_pos_lock_open(p_bill);
  if not exists (select 1 from public.pelham_bill_lines where bill_id = p_bill and active) then
    perform public.pelham_fail('422', 'The bill is empty.');
  end if;

  -- 1) 그린피 줄: 예약마다 잠그고, 플레이어가 아직 낼 수 있는 상태인지 본다.
  for v_booking in
    select distinct li.booking_id from public.pelham_bill_lines li
     where li.bill_id = p_bill and li.kind = 'tee_player' and li.active
     order by 1
  loop
    select t.doc into v_doc from public.pelham_tee_bookings t where t.id = v_booking;
    if v_doc is null then
      perform public.pelham_fail('409', 'A reservation on this bill no longer exists. Remove its line.');
    end if;
    perform public.pelham_tee_lock((v_doc->>'date')::date, v_doc->>'time');
    select t.doc into v_doc from public.pelham_tee_bookings t where t.id = v_booking for update;
    for l in select * from public.pelham_bill_lines li
              where li.bill_id = p_bill and li.booking_id = v_booking and li.kind = 'tee_player' and li.active loop
      v_player := public.pelham_pos_find_player(v_doc, l.player_id);
      if v_player is null then
        perform public.pelham_fail('409', format('%s was removed from the reservation. Remove the line.', l.name));
      end if;
      if coalesce((v_player->>'cancelled')::boolean, false) then
        perform public.pelham_fail('409', format('%s is cancelled. Remove the line.', l.name));
      end if;
      if coalesce((v_player->>'paid')::boolean, false) then
        perform public.pelham_fail('409', format('%s was already marked paid on the tee sheet. Remove the line.', l.name));
      end if;
    end loop;
  end loop;

  perform public.pelham_pos_recalc(p_bill);
  select * into v_bill from public.pelham_bills where id = p_bill;

  -- 2) 결제 검증. 합이 계산서 합계와 같아야 한다(거스름돈은 화면이 계산한다).
  if jsonb_typeof(v_payments) <> 'array' then
    perform public.pelham_fail('422', 'payments must be a list.');
  end if;
  for pay in select value from jsonb_array_elements(v_payments) loop
    v_method := pay->>'method';
    if v_method is null or v_method not in ('cash', 'card', 'debit', 'member_account', 'gift_card', 'rain_check') then
      perform public.pelham_fail('422', format('''%s'' is not a payment method', coalesce(v_method, '')));
    end if;
    v_amount := coalesce((pay->>'amount')::integer, 0);
    if v_amount <= 0 then
      perform public.pelham_fail('422', 'Each payment needs an amount above zero (cents).');
    end if;
    if coalesce((pay->>'tip')::integer, 0) < 0 then
      perform public.pelham_fail('422', 'Tip cannot be negative.');
    end if;
    if v_method in ('card', 'debit') and length(btrim(coalesce(pay->>'auth_code', ''))) = 0 then
      perform public.pelham_fail('422',
        'Card and debit payments need the approval code printed by the Chase terminal.');
    end if;
    if nullif(pay->>'card_last4', '') is not null and (pay->>'card_last4') !~ '^[0-9]{4}$' then
      perform public.pelham_fail('422', 'Card last 4 must be four digits.');
    end if;
    -- 0011: 레인체크는 코드로 잠그고 상태·만료일(매장 현지 날짜)·금액을 본다. 팁은 받지 않는다.
    if v_method = 'rain_check' then
      v_code := upper(btrim(coalesce(pay->>'rain_check_code', '')));
      if v_code = '' then
        perform public.pelham_fail('422', 'A rain check payment needs the code printed on the rain check.');
      end if;
      if v_code = any(v_rc_codes) then
        perform public.pelham_fail('422', format('Rain check %s is on this payment twice.', v_code));
      end if;
      select * into v_rc from public.pelham_rain_checks where code = v_code for update;
      if v_rc.id is null then
        perform public.pelham_fail('404', format('No rain check %s', v_code));
      end if;
      if v_rc.status <> 'issued' then
        perform public.pelham_fail('409', format('Rain check %s is already %s.', v_code, v_rc.status));
      end if;
      if v_rc.expires_on < v_date then
        perform public.pelham_fail('409', format('Rain check %s expired on %s.', v_code, to_char(v_rc.expires_on, 'YYYY-MM-DD')));
      end if;
      if v_amount > v_rc.amount then
        perform public.pelham_fail('422', format('Rain check %s is worth %s cents, not %s.', v_code, v_rc.amount, v_amount));
      end if;
      if coalesce((pay->>'tip')::integer, 0) > 0 then
        perform public.pelham_fail('422', 'Tips cannot be paid with a rain check.');
      end if;
      v_rc_codes := v_rc_codes || v_code;
      v_rc_ids := v_rc_ids || v_rc.id;
    end if;
    v_sum := v_sum + v_amount;
    v_tips := v_tips + coalesce((pay->>'tip')::integer, 0);
  end loop;
  if v_sum <> v_bill.total then
    perform public.pelham_fail('422', format('Payments add up to %s but the bill total is %s (cents).',
                                             v_sum, v_bill.total));
  end if;

  -- 3) 재고. 상품 id 순으로 잠가 두 계산대가 서로를 기다리다 멈추지 않게 한다.
  for l in
    select li.product_id, sum(li.quantity)::integer as qty, min(li.name) as name
      from public.pelham_bill_lines li
     where li.bill_id = p_bill and li.kind = 'product' and li.active
     group by li.product_id order by li.product_id
  loop
    select p2.stock, p2.is_active into v_stock, v_active
      from public.pelham_retail_products p2 where p2.id = l.product_id for update;
    if not v_active then
      perform public.pelham_fail('409', format('%s is no longer for sale. Remove the line.', l.name));
    end if;
    if v_stock is not null and v_stock < l.qty then
      perform public.pelham_fail('409', format('Not enough stock: %s (need %s, %s on hand).', l.name, l.qty, v_stock));
    end if;
  end loop;

  -- 4) 영수증 번호.
  insert into public.pelham_receipt_counters as c (business_date, last_no) values (v_date, 1)
  on conflict (business_date) do update set last_no = c.last_no + 1
  returning last_no into v_no;
  v_receipt := format('PH-%s-%s', to_char(v_date, 'YYYYMMDD'), lpad(v_no::text, 4, '0'));

  -- 5) 기록. 여기부터는 실패할 이유가 없다.
  for l in
    select li.product_id, sum(li.quantity)::integer as qty
      from public.pelham_bill_lines li
     where li.bill_id = p_bill and li.kind = 'product' and li.active
     group by li.product_id order by li.product_id
  loop
    perform public.pelham_pos_move(l.product_id, -l.qty, 'sale', p_bill, v_receipt);
  end loop;

  for pay in select value from jsonb_array_elements(v_payments) loop
    v_method := pay->>'method';
    insert into public.pelham_bill_payments (bill_id, method, amount, tip, entry, auth_code, card_last4, terminal, created_by,
                                             rain_check_id)
    values (p_bill, v_method, (pay->>'amount')::integer, coalesce((pay->>'tip')::integer, 0),
            case when v_method in ('card', 'debit') then 'keyed' else 'none' end,
            nullif(btrim(coalesce(pay->>'auth_code', '')), ''),
            nullif(pay->>'card_last4', ''),
            case when v_method in ('card', 'debit') then 'Chase DX8000' end,
            auth.uid(),
            -- 0011
            case when v_method = 'rain_check' then
              (select r.id from public.pelham_rain_checks r
                where r.code = upper(btrim(coalesce(pay->>'rain_check_code', '')))) end);
  end loop;

  -- 0011: 쓴 레인체크를 이 계산서에 묶는다.
  update public.pelham_rain_checks
     set status = 'redeemed', redeemed_bill_id = p_bill, redeemed_at = now()
   where id = any(v_rc_ids);

  update public.pelham_bills
     set status = 'paid', checkout_id = v_checkout, receipt_no = v_receipt, business_date = v_date,
         tip = v_tips, paid_at = now()
   where id = p_bill;

  -- 티 시트: 계산서에 담긴 사람만 paid. 결제 시각은 서버가 찍는다(0004 와 같다).
  for v_booking in
    select distinct li.booking_id from public.pelham_bill_lines li
     where li.bill_id = p_bill and li.kind = 'tee_player' and li.active
  loop
    select t.doc into v_doc from public.pelham_tee_bookings t where t.id = v_booking;
    select coalesce(jsonb_agg(
             case when exists (select 1 from public.pelham_bill_lines li
                                where li.bill_id = p_bill and li.booking_id = v_booking
                                  and li.player_id = e.value->>'id' and li.kind = 'tee_player' and li.active)
                  then e.value || jsonb_build_object('paid', true, 'paidAt', v_now)
                  else e.value end
             order by e.ord), '[]'::jsonb)
      into v_players
      from jsonb_array_elements(coalesce(v_doc->'players', '[]'::jsonb)) with ordinality as e(value, ord);
    select array_agg(li.name order by li.id) into v_names
      from public.pelham_bill_lines li
     where li.bill_id = p_bill and li.booking_id = v_booking and li.kind = 'tee_player' and li.active;
    v_doc := jsonb_set(v_doc, '{players}', v_players);
    v_doc := public.pelham_tee_audit(v_doc,
               format('Paid on bill %s: %s.', v_receipt, array_to_string(v_names, ', ')), v_now);
    perform public.pelham_tee_save(v_doc);
  end loop;

  return public.pelham_pos_bill_json(p_bill);
end;
$$;

-- ===== 트리거 ==========================================================

-- 계산서 환불과 레인체크. 환불 함수는 계산서 상태를 먼저 바꾸고 그 뒤에 티 시트를 미결제로 돌린다.
-- 그래서 이 트리거가 먼저 레인체크를 무효로 하고, 아래 티 시트 보호는 살아 있는 레인체크를 보지 않는다.
create or replace function public.pelham_rc_on_bill()
returns trigger
language plpgsql
set search_path = ''
as $$
declare
  v_code text;
begin
  if old.status = 'paid' and new.status = 'refunded' then
    -- 이 계산서로 낸 그린피에서 나간 레인체크. 이미 썼으면 돈을 두 번 돌려주게 된다.
    select r.code into v_code from public.pelham_rain_checks r
     where r.source_bill_id = new.id and r.status = 'redeemed'
     limit 1;
    if v_code is not null then
      perform public.pelham_fail('409', format(
        'Rain check %s from this bill was already used. Refund the bill it paid for first.', v_code));
    end if;
    update public.pelham_rain_checks
       set status = 'void', voided_at = now(),
           void_reason = format('Bill %s refunded', coalesce(new.receipt_no, '#' || new.id))
     where source_bill_id = new.id and status = 'issued';
    -- 이 계산서를 낸 레인체크는 다시 쓸 수 있게 된다(만료일은 그대로 — 지났으면 못 쓴다).
    update public.pelham_rain_checks
       set status = 'issued', redeemed_bill_id = null, redeemed_at = null
     where redeemed_bill_id = new.id and status = 'redeemed';
  end if;
  return null;
end;
$$;

drop trigger if exists pelham_rc_on_bill on public.pelham_bills;
create trigger pelham_rc_on_bill
  after update of status on public.pelham_bills
  for each row execute function public.pelham_rc_on_bill();

-- 티 시트 보호. 살아 있는 레인체크가 있는 사람을 미결제로 돌리거나 빼거나 예약을 지우면
-- 크레딧은 남고 낸 돈의 기록만 사라진다. 레인체크를 먼저 무효로 해야 한다.
create or replace function public.pelham_rc_guard_tee()
returns trigger
language plpgsql
set search_path = ''
as $$
declare
  r record;
  v_player jsonb;
begin
  for r in
    select rc.code, rc.player_id, rc.player_name, rc.status from public.pelham_rain_checks rc
     where rc.booking_id = old.id and rc.status in ('issued', 'redeemed')
  loop
    if tg_op = 'DELETE' then
      perform public.pelham_fail('409', format(
        '%s has rain check %s. Void it before deleting the reservation.', r.player_name, r.code));
    end if;
    v_player := public.pelham_pos_find_player(new.doc, r.player_id);
    if v_player is null or not coalesce((v_player->>'paid')::boolean, false) then
      perform public.pelham_fail('409', format(
        '%s has rain check %s. Void it before clearing the payment or removing the player.', r.player_name, r.code));
    end if;
  end loop;
  if tg_op = 'DELETE' then
    return old;
  end if;
  return new;
end;
$$;

drop trigger if exists pelham_rc_guard_tee on public.pelham_tee_bookings;
create trigger pelham_rc_guard_tee
  before update or delete on public.pelham_tee_bookings
  for each row execute function public.pelham_rc_guard_tee();

-- ===== 권한 ============================================================
-- 다시 정의한 0005 함수(bill_json, bill_pay)는 `create or replace` 라 권한이 그대로다.

revoke all on function public.pelham_rc_default_expiry(date) from public, anon, authenticated;
revoke all on function public.pelham_rc_json(public.pelham_rain_checks) from public, anon, authenticated;
revoke all on function public.pelham_rc_paid_value(text, jsonb, jsonb) from public, anon, authenticated;
revoke all on function public.pelham_rc_on_bill() from public, anon, authenticated;
revoke all on function public.pelham_rc_guard_tee() from public, anon, authenticated;

revoke all on function public.pelham_staff_rain_check_quote(text, text) from public, anon, authenticated;
revoke all on function public.pelham_staff_rain_check_issue(jsonb) from public, anon, authenticated;
revoke all on function public.pelham_staff_rain_checks(text) from public, anon, authenticated;
revoke all on function public.pelham_staff_rain_check(text) from public, anon, authenticated;
revoke all on function public.pelham_staff_rain_check_void(text, text) from public, anon, authenticated;

grant execute on function public.pelham_staff_rain_check_quote(text, text) to authenticated;
grant execute on function public.pelham_staff_rain_check_issue(jsonb) to authenticated;
grant execute on function public.pelham_staff_rain_checks(text) to authenticated;
grant execute on function public.pelham_staff_rain_check(text) to authenticated;
grant execute on function public.pelham_staff_rain_check_void(text, text) to authenticated;

notify pgrst, 'reload schema';
